### ISSUE TITLE
rtorrent-flood Job Template apiVersion missing

### ISSUE THREAD

**Issue by binaryronin** [k8s-at-home/charts#1049]
# Details

rtorrent-flood 7.3.0

**Container name and tag:**

`jesec/rtorrent-flood:latest@sha256:5ff0125ea0e2befbc2ba2f2143e130819db645cb5ef68b44a0712b8162a16f47`

**What steps did you take and what happened:**

When trying to install this I get the following error:
```
Error: failed pre-install: unable to build kubernetes object for deleting hook rtorrent-flood/templates/common.yaml: unable to recognize "": no matches for kind "Job" in version ""
```

When rendering out the templates you can see the issue:
```
HOOKS:
---
# Source: rtorrent-flood/templates/common.yaml
---apiVersion: batch/v1
kind: Job
metadata:
  name: rtorrent-flood-autopermissions
  labels:
    helm.sh/chart: rtorrent-flood-7.3.0
    app.kubernetes.io/name: rtorrent-flood
    app.kubernetes.io/instance: rtorrent-flood
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
   "helm.sh/hook": pre-install,pre-upgrade
   "helm.sh/hook-weight": "-10"
   "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
    spec:
      restartPolicy: Never
      containers:
        - name: set-mount-permissions
          image: "alpine:3.3"
          command:
          - /bin/sh
          - -c
          - | 
          #args:
          #
          #securityContext:
          #
          volumeMounts:
          
      volumes:
```

This looks to be the same issue as [951](https://github.com/k8s-at-home/charts/issues/951) and the chart needs to be updated to use the newest common library.
