### ISSUE TITLE
[media-common] Image values separate organisation

### ISSUE THREAD

**Issue by CuBiC3D** [k8s-at-home/charts#106]
In the `media-common` chart the image definitions are as follows:
```
image:
  organization: ""
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""
```
Which separates the organisation part from the image name part. For update automation flux requires the repository value to be in the `owner/image-name` format. I think it would be possible to workaround that, by creating a dummy value for the repository and point flux to use that, but this makes it very hacky and one would need to maintain three repetitive fields for custom images and additional annotations for flux. Were there any specific design decisions to separate them?

**Comment by CuBiC3D** [comment]
Actually the proposed workaround does not seem to work with Flux. I tried for example for radarr:
```yaml
...
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    repository.fluxcd.io/app: image.repo
    tag.fluxcd.io/app: image.tag
    filter.fluxcd.io/app: regexp:^3\.\d+\.\d+\.\d+-ls.*
spec:
  values:
    radarr:
      image:
        # those are chart values concatenated in the pod definition as organization/repository
        organization: linuxserver
        repository: radarr
        # repo is a dummy value(not used by the chart) using the correct notation for a repository
        repo: linuxserver/radarr
        tag: 3.0.0.3624-ls21
...
```
Flux just ignores this and tries to query dockerhub for `index.docker.io/library/radarr` looks like because `values.repository` is already set and a default path to look for in Flux.
```
caller=images.go:159 component=sync-loop err="fetching image metadata for index.docker.io/library/radarr: item not in cache, last error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```
I can't actually workaround that without changing the chart itself.

BTW: Non dockerhub registries can and do contain a longer paths not only consisting of a organisation and a image name, like `cloud/media/custom/radarr` which does not really fit in the `organization` option.
