### ISSUE TITLE
Unifi: PVC annotations and skipuninstall ignored

### ISSUE THREAD

**Issue by hcsaustrup** [k8s-at-home/charts#1080]
# Details

**Helm chart name and version:**

unifi 2.0.4

**Container name and tag:**

jacobalberty/unifi:6.2.25

**What steps did you take and what happened:**

Enabled persistence, requesting a keep policy/skipuninstall (tried both to no avail) on the PVC, but it wasn't annotated and was removed when uninstalling the chart.

**Relevant Helm values:**

```
persistence:
  enabled: true
  size: 10Gi
  storageClass: default-block
  annotations:
    helm.sh/resource-policy: keep
  skipuninstall: true
```

**What did you expect to happen:**

PVC was annotated with keep policy.

**Anything else you would like to add:**

Neither `annotations` nor use of `skipuninstall` is mentioned anywhere in the `pvc.yaml` template of the chart.

**Additional Information:**
