### ISSUE TITLE
Config files from ConfigMaps not updated on change (mosquitto, blocky, ...)

### ISSUE THREAD

**Issue by bkupidura** [k8s-at-home/charts#1090]
# Details

**Helm chart name and version:**

blocky 7.1.0
mosquitto 3.2.0

**Container name and tag:**

spx01/blocky:v0.14
eclipse-mosquitto:2.0.11

**What steps did you take and what happened:**

Some charts (e.g blocky, mosquitto) are using ConfigMap to deliver configs for containers. Updating ConfigMap is not updating config inside container. This is happening because Volumes are mounted with subPath property.

Please check: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

`Note: A container using a ConfigMap as a subPath volume will not receive ConfigMap updates.`

https://github.com/kubernetes/kubernetes/issues/50345

This can lead to some confusion (rerun chart, check ConfigMap, ConfigMap updated, container is using old config).

Is there any reason subPath is in place?

**Relevant Helm values:**

Default values are fine to replicate.

**What did you expect to happen:**

Service config file updated inside container after updating ConfigMap.

**Comment by onedr0p** [comment]
Have you heard of [Reloader](https://github.com/stakater/Reloader) by our friends at Stakater? 

All you need to do it deploy Reloader and set an annotation on the deployment:

`--set  podAnnotations.configmap.reloader.stakater.com/reload="blocky-config"`

Reloader will watch the configmap (or secret if you want) and bounce the pod when it changes.

**Comment by onedr0p** [comment]
I think this will be something we need to implement in the library chart, I opened https://github.com/k8s-at-home/library-charts/issues/78

**Comment by bjw-s** [comment]
We have raised an issue to implement the podAnnotations approach in our charts. This can be tracked under #1095.

The main caveat of course being that the Pod will restart once the configMaps are changed, whereas when not using subPath it can be left up to the application to hot-reload any configuration.

The reason that we use `subPath` is that they have to be mounted into folders where other application files live as well. Maybe this could be worked around on a per-app basis, but that would need further investigating per app.

**Comment by bkupidura** [comment]
@bjw-s maybe instead of subPath, we can use `items`. This will allow us to mount only specific files in mountDir.

```
[...]
          volumeMounts:
            - mountPath: /config
              name: secret
      volumes:
        - name: secret
          secret:
            secretName: recorder-secret
            defaultMode: 0400
            items:
              - key: id_rsa
                path: id_rsa
```

This should work with updating configMaps/secrets inside containers + you will be able to mount only specific keys (files) on filesystem.
