### ISSUE TITLE
[smarter-device-manager] Pods can not start with default configuration

### ISSUE THREAD

**Issue by markafarrell** [k8s-at-home/charts#1092]
# Details

**Helm chart name and version:**
smarter-device-manager 5.1.0

**Container name and tag:**

registry.gitlab.com/arm-research/smarter/smarter-device-manager:v1.20.7

**What steps did you take and what happened:**

`helm install smarter-device-manager k8s-at-home/smarter-device-manager`

Pods could not start due to attempting to use `/dev/termination-log` for `terminationMessagePath` while default configuration causes `/dev/` to be mounted as read-only

**Relevant Helm values:**

Defaults only used

**What did you expect to happen:**

Pods start successfully

**Anything else you would like to add:**

Was able to get pods to start by setting:

```yaml
persistence:
  devfs:
    enabled: true
    type: hostPath
    hostPath: /dev
    readOnly: false
  sysfs:
    enabled: true
    type: hostPath
    hostPath: /sys
    readOnly: true
  kubeletsockets:
    enabled: true
    type: hostPath
    hostPath: "/var/lib/kubelet/device-plugins"
```

I believe that the better solution is to change the path for `terminationMessagePath`. 

The common helm charts, however, do not seem to support this capability

**Additional Information:**
