### ISSUE TITLE
Frigate chart version 5.0.0's value.yaml is confusing around persistence

### ISSUE THREAD

**Issue by hyperbolic2346** [k8s-at-home/charts#1109]
The frigate chart's readme say to look into the value.yaml file for information about persistence, but the [values.yaml ](https://github.com/k8s-at-home/charts/blob/2df5b026b8c08f3aa1818119eefa500c0b401bd8/charts/stable/frigate/values.yaml#L49)has no real information about persistence inside.

```
# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
  media:
    enabled: false
    mountPath: /media
  # -- Configure a hostPathMount to mount a USB device in the container.
  # @default -- See values.yaml
  usb:
    enabled: false
    type: hostPath
    hostPath: /dev/bus/usb
  # -- Configure a temporary cache. See [docs](https://blakeblackshear.github.io/frigate/) for more details..
  # @default -- See values.yaml
  cache:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
    mountPath: /dev/shm
```
Specifically, I was looking to understand what is data vs media. Would I need both? Do I just need one? What gets written to media vs data? This may be something to pass off to the container code like the temporary cache.

The top comment also seems to refer to itself.
