### ISSUE TITLE
[calibre-web] ingress host setting causes helm runtime error

### ISSUE THREAD

**Issue by canh** [k8s-at-home/charts#1114]
# Details

I'm trying to install calibre-web chart onto K3S running on a Raspberry Pi 4 (armf)

**Helm version**
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
**Chart version**
https://artifacthub.io/packages/helm/k8s-at-home/calibre-web/7.3.0

This is my values.yaml:

```
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: calibre-web.example.com
    tls:
      - hosts:
        - calibre-web.example.com
        secretName: calibre-web.example.com
persistence:
  config:
    enabled: true
    existingClaim: config-claim
  books:
    enabled: true
    existingClaim: books-claim
```

`helm template k8s-at-home/calibre-web --namespace calibre-web --values values.yaml`
gives me
`Error: template: calibre-web/templates/NOTES.txt:1:4: executing "calibre-web/templates/NOTES.txt" at <include "common.notes.defaultNotes" .>: error calling include: template: calibre-web/charts/common/templates/_notes.tpl:33:16: executing "common.notes.defaultNotes" at <first .paths>: error calling first: runtime error: invalid memory address or nil pointer dereference
`
Helm can render the template successfully if I remove the
```
    hosts:
      - host: calibre-web.example.com
```
lines, but obviously I need them.

**Comment by jhoos** [comment]
I just ran into this issue on another chart. Adding a `paths` entry to the host in the ingress worked around it, e.g.

```
ingress:
  main:
    hosts:
      - host: host.example.com
        paths:
          - path: /
 ```
