### ISSUE TITLE
bazarr: `config` volume is mounted in the wrong path if `type: hostPath`

### ISSUE THREAD

**Issue by roobre** [k8s-at-home/charts#1116]
# Details

**Helm chart name and version:**

bazarr 9.3.0

**Container name and tag:**

default, `:latest`

**What steps did you take and what happened:**

Filled up the descriptor for the `config` volume.

**Relevant Helm values:**

```yaml
  persistence:
    config:
      enabled: true
      type: hostPath
      hostPath: /mnt/zmir/docker/bazarr/config
      hostPathType: Directory
```

**What did you expect to happen:**

Volume to be mounted in `/config`. However, `_volumemounts.tpl` defaults to mount volumes of type `hostPath` in the same path as the host:

```yaml
        {{/* Set the default mountPath to /<name_of_the_peristence_item> */}}
        {{- $mountPath := (printf "/%v" $persistenceIndex) -}}
        {{- if eq "hostPath" (default "pvc" $persistenceItem.type) -}}
          {{- $mountPath = $persistenceItem.hostPath -}}
        {{- end -}}
```

Which I don't think is particularly useful, but breaks this particular case.

**Anything else you would like to add:**

Trivially fixable by adding `mountPath: /config` to the `values.yml`.

**Additional Information:**
