### ISSUE TITLE
[Octoprint] Error: Invalid value for '--port': tcp://10.43.245.198:80 is not a valid integer

### ISSUE THREAD

**Issue by Nold360** [k8s-at-home/charts#1118]
# Details

**Helm chart name and version:** Octoprint 6.0.0

**Container name and tag:** "octoprint/octoprint:1.6.1"

**What steps did you take and what happened:** Deployed with nearly default values.yaml

**Relevant Helm values:**
```yaml
env:
  TZ: UTC
  ENABLE_MJPG_STREAMER: "true"
  MJPG_STREAMER_INPUT:  # "-y -n -r 640x480"
  CAMERA_DEV:  # /dev/video0

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: vault-issuer
    hosts:
    - host: octoprint.dc
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: octoprint-tls
      hosts:
      - octoprint.dc

securityContext:
  privileged: true

persistence:
  data:
    enabled: true
    mountPath: /octoprint
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
  printer:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyACM0
```

**What did you expect to happen:** Start Octoprint

**Anything else you would like to add:** 
It's clear that he just expects the port number, but i couldn't figure out where it is set & why he is using the service / cluster] IP.

**Additional Information:**
Full Error output:
```
Error: Invalid value for '--port': tcp://10.43.245.198:80 is not a valid integer
Usage: octoprint [OPTIONS] COMMAND [ARGS]...
Try 'octoprint --help' for help.
```
Also it seems to be missing live/readiness probes.

**Comment by yoonst** [comment]
I have the same issue. Looks like port is passed into binary if service is configured within values.yaml file.

```
service:
  main:
    enabled: true
    ports:
      http:
        port: 80
        targetPort: 8080
```

**Comment by bjw-s** [comment]
@Nold360 I have just placed your values in a `helm template . --debug` run, and I can see the liveness/readiness probes showing up:

```yaml
---
# Source: octoprint/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-octoprint
  labels:
    helm.sh/chart: octoprint-6.0.0
    app.kubernetes.io/name: octoprint
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.6.1"
    app.kubernetes.io/managed-by: Helm
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: octoprint
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: octoprint
        app.kubernetes.io/instance: RELEASE-NAME
    spec:

      serviceAccountName: default
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: RELEASE-NAME-octoprint
          image: "octoprint/octoprint:1.6.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: "ENABLE_MJPG_STREAMER"
              value: "true"
            - name: "TZ"
              value: "UTC"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /octoprint
            - name: printer
              mountPath: /dev/ttyACM0
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: RELEASE-NAME-octoprint-data
        - name: printer
          hostPath:
            path: /dev/ttyACM0
```

I have figured out what the cause of your issue is, and it seems to be caused by running an image that was not desgned for Kubernetes in a Kubernetes cluster. The root cause is what is described in the note [over here](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#environment-variables). The Octoprint image looks at the `OCTOPRINT_PORT` env var and decides to pass that along the command line.

This can be solved in a number of ways:

* Specify a manual value for the `OCTOPRINT_PORT` with the correct value
* Set `enableServiceLinks` to `false`
