### ISSUE TITLE
[traefik-forward-auth] providers.google.client-id, providers.google.client-secret must be set

### ISSUE THREAD

**Issue by MatteoGioioso** [k8s-at-home/charts#1165]
# Details

**Helm chart name and version:**

traefik-forward-auth latest version

**Container name and tag:**

`thomseddon/traefik-forward-auth:latest`

**What steps did you take and what happened:**
Just deployed the chart

**Relevant Helm values:**
```
traefik-forward-auth:
  providers:
    google:
      enabled: false
    oidc:
      enabled: true
      clientId: xxxxx
      clientSecret: xxxxxx
      issuerUrl: xxxx
      resource: ....

  image:
    tag: latest
    repository: thomseddon/traefik-forward-auth
    pullPolicy: Always
```

**What did you expect to happen:**
To at least get the container starting, however from the logs I have this error:

```
providers.google.client-id, providers.google.client-secret must be set
```

As far as I know this image should support OIDC: https://github.com/thomseddon/traefik-forward-auth#openid-connect

Any ideas? Thanks
