### ISSUE TITLE
[home-assistant] Prometheus integration is not enabled when metrics are enabled

### ISSUE THREAD

**Issue by jvalskis** [k8s-at-home/charts#1247]
# Details

**Helm chart name and version:**

home-assistant 11.0.4

**Container name and tag:**

homeassistant/home-assistant:2021.6.3

**Relevant Helm values:**

```yaml
  metrics:
    enabled: true
    serviceMonitor:
      bearerTokenSecret:
        name: home-assistant-prometheus-access-token
        key: token
```

**What did you expect to happen:**

When `metrics` setting is enabled I assumed it would just work, but prometheus kept alerting - `api/prometheus` returned 404. Apparently one needs to enable prometheus integration for home-assistant in its settings (`/config/configuration.yaml`). See https://www.home-assistant.io/integrations/prometheus/
E.g.:

```yaml
prometheus:
  namespace: hass
```

It would be nice, if this happened automagically - enabling metrics, would enable the integration.
