### ISSUE TITLE
ser2sock docs wrong

### ISSUE THREAD

**Issue by runningman84** [k8s-at-home/charts#1249]
# Details

**Helm chart name and version:**

ser2sock 5.x

**What steps did you take and what happened:**

The docs still mention this:
```
additionalVolumeMounts:
  - name: usb
    mountPath: /path/to/device

additionalVolumes:
  - name: usb
    hostPath:
      path: /path/to/device
```

but the new settings are
```
persistence:
  usb:
    enabled: true
    type: hostPath
    mountPath:  /path/to/device
```
