### ISSUE TITLE
Problem with Google Auth

### ISSUE THREAD

**Issue by fabricesemti80** [k8s-at-home/charts#1270]
# Details

**Helm chart name and version:**

- traefik-forward-auth-1.0.10

**Container name and tag:**

- thomseddon/traefik-forward-auth

**What steps did you take and what happened:**

- registered  a Google app with the following authorised URL:

https://auth.this-is-my-domain.com/_oauth (obviously this is not the real domain)

- deployed this chart with the following values:

```yaml
# Default values for traefik-forward-auth.
#&  --> helm install traefik-forward-auth k8s-at-home/traefik-forward-auth -f values.yaml
replicaCount: 1

image:
  repository: thomseddon/traefik-forward-auth
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logging:
  # logging.level -- [trace|debug|info|warn|error|fatal|panic] Log level (default: warn)
  level: "debug"
  # logging.format -- [text|json|pretty] Log format (default: text)
  format: "pretty"
# authHost -- Single host to use when returning from 3rd party auth
authHost: "auth.this-is-my-domain.com"
restrictions:
  # restrictions.domain -- Only allow given email domains. (Comma delimited)
  domain: "*"
  # restrictions.whitelist -- Only allow given email addresses. (Comma delimited)
  whitelist: "thisis@myemail.com"
# lifetime -- Lifetime in seconds (default: 43200)
lifetime: ""
cookie:
  # cookie.domain -- Domain(s) to set auth cookie on. (Comma delimited)
  domain: "this-is-my-domain.com"
  # cookie.insecure -- Use insecure cookies # ?
  insecure: "true"
  # cookie.name -- Cookie Name (default: _forward_auth)
  name: ""
  # cookie.csrfName -- CSRF Cookie Name (default: _forward_auth_csrf)
  csrfName: ""
  # cookie.secret -- Cookie Secret used for authentication across multiple instances / clusters (default: randomly generated)
  secret: ""
default:
  # default.action -- [auth|allow] Default action (default: auth)
  action: ""
  # default.provider -- [google|oidc|generic-oauth] Default provider (default: google)
  provider: ""
# logoutRedirect -- URL to redirect to following logout
logoutRedirect: ""
# urlPath -- Callback URL Path (default: /_oauth)
urlPath: ""
# secret -- Secret used for signing. If empty, one will be generated. If specifying your own in env use "-"
secret: "this-is-something-random"

middleware:
  # middleware.enabled -- Enable to deploy a preconfigured middleware
  enabled: true #false
  # middleware.name -- Name for the middleware
  name: ""
providers:
  google:
    # providers.google.enabled -- Enable the google provider
    enabled: true #false
    # providers.google.clientId -- Client ID
    clientId: "this-is-my-client-id"
    # providers.google.clientSecret -- Client Secret
    clientSecret: "this-is-my-client-secret"
    # providers.google.prompt -- Space separated list of OpenID prompt options
    prompt: ""
  oidc:
    # providers.oidc.enabled -- Enable the generic OIDC provider
    enabled: false
    # providers.oidc.issuerUrl -- Issuer URL
    issuerUrl: ""
    # providers.oidc.clientId -- Client ID
    clientId: ""
    # providers.oidc.clientSecret -- Client Secret
    clientSecret: ""
    # providers.oidc.resource -- Optional resource indicator
    resource: ""
  genericOauth:
    # providers.genericOauth.enabled -- Enable the generic OAUTH2 provider
    enabled: false
    # providers.genericOauth.authUrl -- Auth/Login URL
    authUrl: ""
    # providers.genericOauth.tokenUrl -- Token URL
    tokenUrl: ""
    # providers.genericOauth.userUrl -- URL used to retrieve user info
    userUrl: ""
    # providers.genericOauth.clientId -- Client ID
    clientId: ""
    # providers.genericOauth.clientSecret -- Client Secret
    clientSecret: ""
    # providers.genericOauth.scope -- Scopes (default: profile, email)
    scope: ""
    # providers.genericOauth.tokenStyle -- How token is presented when querying the User URL
    tokenStyle: ""
    # providers.genericOauth.resource -- Optional resource indicator
    resource: ""

env: []
envFrom:
# - secretRef:
#     name:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# livenessProbe -- Liveness probe configuration
# @default -- {"periodSeconds":20,"tcpSocket":{"port":"http"}}
livenessProbe:
  # livenessProbe.enabled -- Enable liveness probe
  enabled: true
  tcpSocket:
    port: http
  periodSeconds: 20

# readinessProbe -- Readiness probe configuration
# @default -- {"periodSeconds":10,"tcpSocket":{"port":"http"}}
readinessProbe:
  # readinessProbe.enabled -- Enable readiness probe
  enabled: true
  tcpSocket:
    port: http
  periodSeconds: 10

service:
  type: ClusterIP
  port: 4181
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  additionalSpec: {}

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: auth.this-is-my-domain.com #chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```

Got error,

**Relevant Helm values:**

**What did you expect to happen:**

Authenticated via Google

**Anything else you would like to add:**

The browser asked for credentials, logged in as my Google account, but then got the pictured issue: https://i.imgur.com/N0dQpvL.png

(sanitized ) pod logs show this:

```sh
time="2021-11-10T20:27:48Z" level=debug msg="Authenticating request" cookies="[auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJsb2NhbGUiOiJlbiIsInZpZXdNb2RlIjoibW9zYWljIiwic2luZ2xlQ2xpY2siOmZhbHNlLCJwZXJtIjp7ImFkbWluIjp0cnVlLCJleGVjdXRlIjp0cnVlLCJjcmVhdGUiOnRydWUsInJlbmFtZSI6dHJ1ZSwibW9kaWZ5Ijp0cnVlLCJkZWxldGUiOnRydWUsInNoYXJlIjp0cnVlLCJkb3dubG9hZCI6dHJ1ZX0sImNvbW1hbmRzIjpbXSwibG9ja1Bhc3N3b3JkIjpmYWxzZSwiaGlkZURvdGZpbGVzIjpmYWxzZSwiZGF0ZUZvcm1hdCI6ZmFsc2V9LCJleHAiOjE2MzY1ODA4NzgsImlhdCI6MTYzNjU3MzY3OCwiaXNzIjoiRmlsZSBCcm93c2VyIn0.VzkGQMA84ffoz4LySCA-nhc7qzgXb74kpWEu4Sb2hZQ _forward_auth_csrf=0cd162d500dff2e7da45a18b67586752]" handler=Auth host=filebrowser.-THIS-IS-MY-DOMAIN method=GET proto=https rule=default source_ip=141.101.105.14 uri=/
time="2021-11-10T20:27:48Z" level=debug msg="Set CSRF cookie and redirected to provider login url" csrf_cookie="_forward_auth_csrf=51f298c53ca67ccb64125753a66454d9; Path=/; Domain=-THIS-IS-MY-DOMAIN; Expires=Thu, 11 Nov 2021 08:27:48 GMT; HttpOnly" handler=Auth host=filebrowser.-THIS-IS-MY-DOMAIN login_url="https://accounts.google.com/o/oauth2/auth?client_id=-THIS-IS-MY-CLIENT-ID&prompt=select_account&redirect_uri=https%3A%2F%2Fauth.-THIS-IS-MY-DOMAIN%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=51f298c53ca67ccb64125753a66454d9%3Agoogle%3Ahttps%3A%2F%2Ffilebrowser.-THIS-IS-MY-DOMAIN%2F" method=GET proto=https rule=default source_ip=141.101.105.14 uri=/
```

**Additional Information:**
