### ISSUE TITLE
Wikijs not launching

### ISSUE THREAD

**Issue by rlex** [k8s-at-home/charts#1283]
# Details

wikijs-6.0.1

ghcr.io/linuxserver/wikijs:2.5.219

Tried to launch wikijs

```yaml
- image:
          tag: 2.5.219
      - ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: wjs.example.org
                paths:
                  - path: /
                    pathType: Prefix
      - persistence:
          data:
            enabled: true
            mountPath: /app/wiki/data
            type: pvc
            accessMode: ReadWriteOnce
            storageClass: longhorn
            size: 1Gi
```

**What did you expect to happen:**

Wikijs should launch

**Additional Information:**

```
internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module '/app/wiki/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by onedr0p** [comment]
Any help debugging or creating a PR to fix it would be great, but maybe it's an upstream issue with the app?

**Comment by rlex** [comment]
I tried launching image directly on docker, launched correctly. Hasn't tested initial setup but at least it started

**Comment by rlex** [comment]
Okay, while trying node-red faced similar problem, managed to fix nodered by setting 
```
      - podSecurityContext:
          runAsUser: 1880
          runAsGroup: 1880
          fsGroup: 0
```

It seems longhorn is somehow related - if i use longhorn for data/config pvc, it launches, but in case of longhorn faults. No errors on init stage, sadly.

**Comment by rlex** [comment]
I managed to launch it correctly with following:
```
      - env:
          DATAPATH: "/data"
          DB_TYPE: sqlite
          DB_FILEPATH: "/data/db.sqlite"
      - persistence:
          data:
            enabled: true
            mountPath: /data
            type: pvc
            accessMode: ReadWriteOnce
            storageClass: longhorn
            size: 1Gi
          config:
            enabled: false
```
That way it stores both static content like images and etc and sqlite database under /data mountpoint.  
It seems like there is some overlap (?) while mounting /app/wiki/data. If you do not mount anything into /app/wiki folder, then it works.   
I'm also not quite sure why /config is even need mount. Majority of settings are stored in database anyway. It makes sense if wiki writes from app to .yml, but it seems it doesn't.   
Without /config mount it still throws:
```
[cont-init.d] 50-config: executing... 
New container detected. Setting up app folder and fixing permissions.
```
...But loads correctly with persistence.

Not quite sure what causes this behaviour due to increased complexity of container (s6 init, all that stuff) and the fact it doesn't really throws any errors on init stage.
