### ISSUE TITLE
double-take please make compreface optional 

### ISSUE THREAD

**Issue by runningman84** [k8s-at-home/charts#1314]
# Details

**Helm chart name and version:**
double-take-1.1.0

**Container name and tag:**
1.6.0

**What steps did you take and what happened:**
Install double-take and try to use facebox instead of compreface.

These are the errors in the logfile:
```
double-take error: detectors.compreface.url is not of a type(s) string   
double-take error: notify.gotify.url is not of a type(s) string    
```

**Relevant Helm values:**
```
image:
  repository: jakowenko/double-take
  tag: 1.7.0
env:
  TZ: "Europe/Berlin"
config:
  mqtt:
    host: mosquitto
  frigate:
    url: http://frigate:5000
  detectors:
    # compreface:
    #   url: http://compreface:8080
    # deepstack:
    #   url: http://deepstack:5000
    facebox:
      url: http://facebox:8080
```

**What did you expect to happen:**
The helm chart should not add a compreface section if there is no url specified.

**Anything else you would like to add:**
The same issue happens with the gotify stuff,

**Additional Information:**
