### ISSUE TITLE
k8s-at-home base chart

### ISSUE THREAD

**Issue by xeor** [k8s-at-home/charts#1317]
# Details

**Describe the solution you'd like:**

The library-common chart is very useful, even in it's basic form with it's addons and structure.. It would be nice with a `base` chart that is just a "blank". Ie, used when you just have a container-image, but no helm chart.
Example, the `appdaemon` chart has nothing special to it. It just uses the basic library-common chart.

That way, I could refeer to a base-chart, like

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: a-random-app
spec:
  chart:
    spec:
      chart: base
      version: 11.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: namespace/randomapp
      tag: 123
  ...
```

and get all the k8s-at-home goodieness that is in the common chart.

**Anything else you would like to add:**

This might already exist, but I coulnt find it. The library chart also states that `WARNING: THIS CHART IS NOT MEANT TO BE INSTALLED DIRECTLY`
