### ISSUE TITLE
Searx: info leak: generates http (non-ssl) links

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/charts#1326]
# Details

**Helm chart name and version:**
searx 5.3.0

**Container name and tag:**
searx/searx:1.0.0-211-968b2899
caddy:2.2.0-alpine
dalf/filtron:latest
dalf/morty:latest

**What steps did you take and what happened:**
With `searx.baseUrl` and `searx.mortyurl` both set to https, searx is generating ~all~ several fully-qualified links as unencrypted http. This includes the template used for "add as a search engine".

For example (from view-source):
```
<link rel="alternate" type="application/rss+xml" title="Searx search: test potato" href="http://searx.goes.here/search?q=test%20potato&amp;categories=general&amp;language=en-US&amp;format=rss">
```

This is especially dangerous when used as a browser search engine because it will transparently leak all of the search queries prior to any redirection.

**Relevant Helm values:**
```
    caddy:
      noTls: true
    searx:
      baseUrl: "https://${service_host}"
      mortyKey: .....
    env:
      TZ: "America/New_York"
      BASE_URL: "https://${service_host}"
      # This has no impact:
      SEARX_HOSTNAME: "${service_host}"
      MORTY_URL: "https://${service_host}/morty/"
      AUTOCOMPLETE: "duckduckgo"
```

**What did you expect to happen:**

Fully-qualified urls are all prefaced by `BASE_URL`.

**Anything else you would like to add:**

On a spot check, these links are http:
- alternate rss (as above)
- RSS subscription link under `Links`
- Preferences "Search URL of the currently saved preferences"

The `/morty/` links are all correctly https.

**Additional Information:**

Including a note in the documentation about the privacy dangers of automatic redirects for this specific application might be worthwhile. It seems reasonable that most people running their own search instances do not want their searches broadcast unencrypted across the web.
