### ISSUE TITLE
qbittorrent is failing healthcheck

### ISSUE THREAD

**Issue by halkeye** [k8s-at-home/charts#1338]
# Details

**Helm chart name and version:**

k8s-at-home/qbittorrent
13.1.0

**Container name and tag:**

ghcr.io/k8s-at-home/qbittorrent:v4.3.9

**What steps did you take and what happened:**

Enabled OpenVPN

**Relevant Helm values:**

```
env:
  WAIT_FOR_VPN: "true"

addons:
  vpn:
    enabled: true
    # This Should be set to `openvpn`. This will set the add-on to use the default settings for OpenVPN based connections.
    type: openvpn

    openvpn:
      image:
        repository: halkeye/openvpn-client

    # If the podSecurityContext is set to run as a different user, make sure to run the OpenVPN container as root.
    # This is required for it to be able to read certain configuration files.
    securityContext:
      runAsGroup: 0
      runAsUser: 0

    env:
      # Set this environment variable to 'on' to make sure all traffic gets routed through the VPN container.
      # Make sure to check the other environment variables for the OpenVPN image to see how you can exclude certain
      # traffic from these firewall rules.
      FIREWALL: "on"

    # The scripts that get run when the VPN connection opens/closes are defined here.
    # The default scripts will write a string to represent the current connection state to a file.
    # Our qBittorrent image has a feature that can wait for this file to contain the word 'connected' before actually starting the application.
    scripts:
      up: |-
        #!/bin/bash
        /etc/openvpn/up.sh
        echo "connected" > /shared/vpnstatus

      down: |-
        #!/bin/bash
        /etc/openvpn/down.sh
        echo "disconnected" > /shared/vpnstatus

```

**What did you expect to happen:**

Pod to stay up cause probes are working

**Anything else you would like to add:**

kubectl describe says `Startup probe failed: dial tcp 10.244.117.172:8080: i/o timeout` which makes me think it has something todo with OpenVPN firewall being enabled?

**Additional Information:**

possible solutions: switch to `curl localhost` liveness probe, which seems to work just fine.
