### ISSUE TITLE
[gollum] seems there are missing values in values.yaml?

### ISSUE THREAD

**Issue by jboesh** [k8s-at-home/charts#1339]
**Helm chart name and version:**
gollum:3.1.0
https://github.com/k8s-at-home/charts/tree/master/charts/stable/gollum

Hi
Iam trying to deploy the gollum chart from your repository. but it seems there are missing values in values.yaml.
I can set Ingress to enabled, but that's about it.
for example where do I put the hostname and secret name?
![image](https://user-images.githubusercontent.com/71582854/147752104-412e2763-6b6b-4d00-99af-f9440ffeaf00.png)

When I put this on Enabled then I see the Ingress resource being created (in argocd in my case)
but I cant edit the resource..
![image](https://user-images.githubusercontent.com/71582854/147752174-27ed6bb2-bcbe-42c2-af78-db8b651d669e.png)
so I need to fill in the hostname and my annotations at least...

**Comment by bjw-s** [comment]
As stated in the comment in the top of our [charts' values.yaml] (https://github.com/k8s-at-home/charts/blob/master/charts/stable/gollum/values.yaml#L1L6), almost all our charts inherit their default values from [our common library](https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml) and (almost) only specify where they differ.

**Comment by jboesh** [comment]
OK Ive seen the common values.
So I assume that I can copy paste the ingress values from the common-values in the values.yaml?
But when I do that it gives me an error:
`Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in :`

So I only need to configure the ingress for the Gollum chart, this is my current values file:
I dont get it, it looks valid right?
```
ingress:
  main:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: gollum.mydomain.com
    tls:
      - secretName: gollum-prod-tls
        hosts:
          - gollum.mydomain.com

```

**Comment by bjw-s** [comment]
I am guessing that you are missing a `paths' key. Give this a try:

```yaml
ingress:
  main:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: gollum.mydomain.com
        paths:
          - path: /
    tls:
      - secretName: gollum-prod-tls
        hosts:
          - gollum.mydomain.com
```
