### ISSUE TITLE
[ghost] Missing PVC

### ISSUE THREAD

**Issue by Brice187** [k8s-at-home/charts#1358]
# Details

**Helm chart name and version:**

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ghost
  version: 1.1.0
  repo: https://k8s-at-home.com/charts/
  valuesFile: values.yaml
  namespace: ghost
  releaseName: ghost
```

Running `kustomize build --enable-helm` creates following yaml(-snippet):
```yaml
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ghost
    app.kubernetes.io/version: 4.27.2
    helm.sh/chart: ghost-1.1.0
  name: ghost
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: ghost
      app.kubernetes.io/name: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ghost
        app.kubernetes.io/name: ghost
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: database__client
          value: mysql
        - name: database__connection__database
          value: ghost
        - name: database__connection__host
          value: ghost-mariadb
        - name: database__connection__password
          value: XXXXXXXXXXXXX_
        - name: database__connection__user
          value: ghost
        - name: url
          value: http://ghost.local
        image: ghost:4.27.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 2368
          timeoutSeconds: 1
        name: ghost
        ports:
        - containerPort: 2368
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 2368
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 2368
          timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: default
...
```
^ No PVC referenced in the Deployment

**Relevant Helm values:**

values.yaml
```yaml
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghost
  # -- image tag
  tag: 4.27.2
  # -- image pull policy
  pullPolicy: IfNotPresent
...
# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  content:
    enabled: true
    mountPath: /var/lib/ghost/content
...
```

**Container name and tag:**

ghost:4.27.2

**What steps did you take and what happened:**

When `kustomization.yaml` is applied, no pvc gets created:

```
lars@Larss-MacBook-Air ghost % kubectl -n ghost get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-ghost-mariadb-0   Bound    pvc-387dd6a2-901c-4b86-bdf9-b8876f597a3d   8Gi        RWO            local-path     14d
```

**What did you expect to happen:**

Creation of a PV 

**Anything else you would like to add:**

**Additional Information:**
