### ISSUE TITLE
Run Multiple Pod-Gateway VPN Helm Charts

### ISSUE THREAD

**Issue by Vertiwell** [k8s-at-home/charts#1377]
# Details

**Helm chart name and version:**

k8s-at-home/pod-gateway 5.2.0

**What steps did you take and what happened:**

Attempted to run two pod-gateway helm charts, each with it's own unique VPN.
Everything seems to work except sidecar pods are not spawned to the targeted second charts namespace.

**Relevant Helm values:**

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
  labels:
    routed-gateway: "true"
---
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn2
  labels:
    routed-gateway2: "true"
---
DNS: 172.16.0.1
routed_namespaces:
- vpn
settings:
  VXLAN_ID: 42
  VXLAN_IP_NETWORK: "172.16.0"
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_LOCAL_CIDRS: "10.43.0.0/16 192.168.1.0/24"
  VXLAN_GATEWAY_FIRST_DYNAMIC_IP: 120
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.43.0.0/16 192.168.1.0/24"
webhook:
  namespaceSelector:
    type: label
    label: "routed-gateway"

helm install --namespace gateway pod-gateway k8s-at-home/pod-gateway -f gateway-values.yaml

---
DNS: 173.16.0.1
routed_namespaces:
- vpn2
settings:
  VXLAN_ID: 43
  VXLAN_IP_NETWORK: "173.16.0"
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_LOCAL_CIDRS: "10.43.0.0/16 192.168.1.0/24"
  VXLAN_GATEWAY_FIRST_DYNAMIC_IP: 120
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.43.0.0/16 192.168.1.0/24"

webhook:
  namespaceSelector:
    type: label
    label: "routed-gateway2"

helm install --namespace gateway2 pod-gateway2 k8s-at-home/pod-gateway -f gateway-values2.yaml

```
**What did you expect to happen:**
gateway-sidecar and or gateway-init was added to pods in namespace vpn, but not vpn2

I did try many combination of various options and things, however couldn't find any errors or issues that were preventing the deployment.

**Additional Information:**

**Comment by angelnu** [comment]
Hi @Vertiwell , could you check if the webhook Pod was deployed for vpn-2? If yes, then please collect its logs after adding a Pod to the vpn-2 namespace inckuding the routed-gateway2 label.

**Comment by Vertiwell** [comment]
Hi @angelnu, 
I have no idea why, but it's magically working now, I'm just going to go have a little cry.
Thanks for the response.

**Comment by Vertiwell** [comment]
The fix was to change:
```
webhook:
  namespaceSelector:
    type: label
    label: "routed-gateway2"
  gatewayLabel: setGateway2
  gatewayAnnotation: setGateway2
```

From the helm chart: https://github.com/k8s-at-home/charts/blob/master/charts/stable/pod-gateway/values.yaml
