### ISSUE TITLE
[vaultwarden] Add `ADMIN_TOKEN` variable to `values.yaml`

### ISSUE THREAD

**Issue by MurzNN** [k8s-at-home/charts#1393]
# Details

`vaultwarden` container uses `ADMIN_TOKEN` environment value for admin interface access, but setting it is not defined in chart.

https://github.com/dani-garcia/vaultwarden/blob/0876d4a5fd0f5148919360a2912d48b994148d5f/.env.template#L224

**Helm chart name:** vaultwarden

**Describe the solution you'd like:**

Will be good to add the `ADMIN_TOKEN` variable to `values.yaml` template with comment what it is. And even better to store it in separate Secrets item, instead of pod's ENV variables.

**Comment by bjw-s** [comment]
We purposely don't add all available ENV vars to our charts. Instead, we reference to the upstream documentation to provide information [about what is available](https://github.com/k8s-at-home/charts/blob/master/charts/stable/vaultwarden/values.yaml#L19).

Having the value in a secret can be achieved by specifying these values in your `values.yaml`:
```yaml
env:
  ADMIN_TOKEN:
    valueFrom:
      secretKeyRef:
        name: <your secret name>
        key: <the key in that secret>
```
