### ISSUE TITLE
[Helm Chart] Homer Dashboard - Upgrade fails from 6.0.1 > 7.1.0

### ISSUE THREAD

**Issue by weyderfs** [k8s-at-home/charts#1394]
# Details

**Helm chart name and version:**: `k8s-at-home/homer:7.1.0`

**Container name and tag:**: `b4bz/homer:21.09.2`

**What steps did you take and what happened:**

Upgrade fails and the console output is:
```
coalesce.go:199: warning: cannot overwrite table with non table for config (map[data:map[config.yml:externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
] enabled:false])
coalesce.go:199: warning: cannot overwrite table with non table for config (map[data:map[config.yml:externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
] enabled:false])
Error: UPGRADE FAILED: template: homer/templates/common.yaml:23:34: executing "homer/templates/common.yaml" at <include "homer.harcodedValues" .>: error calling include: template: homer/templates/common.yaml:6:16: executing "homer.harcodedValues" at <.Values.configmap.config.enabled>: can't evaluate field enabled in type interface {}
```

**Relevant Helm values:**

```
env:
  # -- Set the container timezone
  TZ: America/Sao_Paulo
  # -- Specify the user ID the application will run as
  UID: "1001"
  # -- Specify the group ID the application will run as
  GID: "1001"

---

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    readOnly: false
    retain: false
    mountPath: /www/assets

---

configmap:
  # -- Store homer configuration as a ConfigMap
  enabled: true
  # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
  # @default -- See values.yaml
  # config: |
  #   externalConfig: #https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
  config: | 
    [.........]
```
