### ISSUE TITLE
Emby ffmpeg issue. "Playback Error: No compatible streams are currently available"

### ISSUE THREAD

**Issue by Kamaroth92** [k8s-at-home/charts#1431]
# Details

**Helm chart name and version:**
emby 3.2.0

**Container name and tag:**
ghcr.io/k8s-at-home/emby v4.6.1.0

**What steps did you take and what happened:**
Helm install (via argo) using pre-existing pvc mounts for the media drive. I let the chart create the config mount.
When trying to stream I got the error "Playback Error: No compatible streams are currently available" 
Looking at the logs in emby it looked like ffmpeg wasn't able to load shared libraries, the output of ldd confirms the same.
```
kah@emby-7f69ddbb8b-kngzk:/app$ ldd ffmpeg
        linux-vdso.so.1 (0x00007ffd95bf7000)
        libavdevice.so.58 => not found
        libavfilter.so.7 => not found
        libavformat.so.58 => not found
        libavcodec.so.58 => not found
        libpostproc.so.55 => not found
        libswresample.so.3 => not found
        libswscale.so.5 => not found
        libavutil.so.56 => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe392da3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe392d80000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe392b8e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe392ef9000)
```

**Relevant Helm values:**

```
        env:
          TZ: Australia/Melbourne
        ingress:
          main:
            enabled: true
            ingressClassName: kong
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
            - secretName: emby-tls
              hosts:
              - emby.mydomain
            hosts:
              - host: emby.mydomain
                paths:
                - path: /
        persistence:
          config:
            enabled: true
            size: 1Gi
          media:
            enabled: true
            existingClaim: media-server-media

```

**Anything else you would like to add:**
I changed the image to use the latest emby image with the below helm values and it just worked; no other changes made. 
```
        image:
          repository: emby/embyserver
          tag: 4.7.0.24
```
