### ISSUE TITLE
[dendrite] image tag is not followed when creating a polylith deployment

### ISSUE THREAD

**Issue by rikhwanto** [k8s-at-home/charts#1448]
# Details

**Helm chart name and version:**
`k8s-at-home/dendrite:3.0.1`

**Container name and tag:**
`matrixdotorg/dendrite-polylith:v0.6.3`

**What steps did you take and what happened:**
1. Create a values.yaml file for a Dendrite polylith deployment (`dendrite.polylithEnabled: true`)
2. Specify image tag for components of Dendrite (eg: `clientapi.image.tag: latest`)
3. Install k8s-at-home/dendrite chart with values.yaml

**Relevant Helm values:**
```
dendrite:
  polylithEnabled: true

appserviceapi:
  image:
    pullPolicy: Always
    tag: latest
  config:
    config_files: []

clientapi:
  image:
    pullPolicy: Always
    tag: latest

eduserver:
  image:
    pullPolicy: Always
    tag: latest

federationapi:
  image:
    pullPolicy: Always
    tag: latest

keyserver:
  image:
    pullPolicy: Always
    tag: latest

mediaapi:
  image:
    pullPolicy: Always
    tag: latest
```

**What did you expect to happen:**
Pods to be created with container image of `matrixdotorg/dendrite-polylith:latest` instead of `matrixdotorg/dendrite-polylith:v0.6.3`

**Anything else you would like to add:**
Running `helm template` also generate a YAML where the containers have value of `image: "matrixdotorg/dendrite-polylith:v0.6.3"` no matter what the `.image.tag` value is.

**Additional Information:** -
