### ISSUE TITLE
wikijs helm chart's values.env overrides values.secrets

### ISSUE THREAD

**Issue by halkeye** [k8s-at-home/charts#1455]
# Details

**Helm chart name and version:**

wikijs-6.2.0

**Container name and tag:**

ghcr.io/linuxserver/wikijs:version-2.5.201

**What steps did you take and what happened:**

Wanting to store database as a secret, I switched from env to secrets

**Relevant Helm values:**

```
secret:
  DB_HOST: postgresql.databases.svc.cluster.local
  DB_NAME: wikijs
  DB_TYPE: postgres
  DB_USER: wikijs
# plus actual secrets like passwords
```

**What did you expect to happen:**

pod's env is populated

**Anything else you would like to add:**

pod spec
```
  - env:
    - name: DB_FILEPATH
      value: /app/wiki/data/db.sqlite
    - name: DB_NAME
    - name: DB_PASS
    - name: DB_PASS_FILE
    - name: DB_PORT
    - name: DB_SSL
    - name: DB_SSL_CA
    - name: DB_TYPE
      value: sqlite
    - name: DB_USER
    - name: TZ
      value: America/Vancouver
    envFrom:
    - secretRef:
        name: wikijs
 
 ```

but when running export on the pod:

```
declare -x DB_FILEPATH="/app/wiki/data/db.sqlite"
declare -x DB_HOST="postgresql.databases.svc.cluster.local"
declare -x DB_NAME=""
declare -x DB_PASS=""
declare -x DB_PASS_FILE=""
declare -x DB_PORT=""
declare -x DB_SSL=""
declare -x DB_SSL_CA=""
declare -x DB_TYPE="sqlite"
declare -x DB_USER=""
```

Maybe common chart needs to be updated to exclude env that are also in the secret hash? or maybe the values for this chart need to not the keys pre-defined?
