### ISSUE TITLE
Error installing filebrowser

### ISSUE THREAD

**Issue by MrMarble** [k8s-at-home/charts#1458]
# Details

**Helm chart name and version:** filebrowser 1.2.0

**Container name and tag:** filebrowser/filebrowser v2.18.0

**What steps did you take and what happened:**
I tried deploying filebrowser as part of my cluster with helm and flux, this are the config files I used:

<details>
  <summary>helm-values.yaml</summary>

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: filebrowser
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: &host "filebrowser.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: "filebrowser-tls" # Kubernetes secret where SSL cert will be stored
        annotations:
          hajimari.io/icon: "text-box-search" # Hajimari dashboard custom icon
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure" # Use HTTPS
          cert-manager.io/cluster-issuer: "letsencrypt-production" # Request SSL Certificate

      env:
        TZ: ${TIMEZONE}
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config-v1
        mountpath: /config
      data:
        enabled: true
        type: custom
        volumeSpec:
          hostPath:
            type: DirectoryOrCreate
            path: /mnt/media

```  
</details>

<details>
  <summary>filebrowser.pvc.yaml</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-v1
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

```  
</details>

The HelmRelease fails with this message:

`Helm uninstall failed: uninstall: Release not loaded: filebrowser: release: not found`

If I run `kubectl get helmrelease -n media filebrowser -o yaml` I can see this message:

`Helm install failed: template: filebrowser/templates/NOTES.txt:1:4: executing "filebrowser/templates/NOTES.txt" at <include "common.notes.defaultNotes" .>: error calling include: template: filebrowser/charts/common/templates/_notes.tpl:33:16: executing "common.notes.defaultNotes" at <first .paths>: error calling first: runtime error: invalid memory address or nil pointer dereference
`
