### ISSUE TITLE
[homebridge] startup.sh is not mounted as executable

### ISSUE THREAD

**Issue by seanson** [k8s-at-home/charts#1465]
# Details

homebridge 4.3.0

**Container name and tag:**
name: homebridge
tag: `ghcr.io/oznu/homebridge:latest@sha256:4703dca68510307587361f4312e6bad0e765e85f8986a7517e0f393d8d0e2410`

**What steps did you take and what happened:**

Enable persistence and set a startup.sh script in the config stanza.
The application will boot as normal but silently fail because the upstream container expects to be able to `chmod +x`: https://github.com/oznu/docker-homebridge/blob/71e8eb26d4ee8eeb1adf0972b70e70ef261c3858/root/etc/cont-init.d/45-user-data#L11

**Relevant Helm values:**
```yaml
persistence:
  config:
    enabled: true
config: |
  #!/bin/sh
  echo "This message will not appear in the logs"
```
**What did you expect to happen:**

Startup script should execute

**Anything else you would like to add:**

**Additional Information:**
