### ISSUE TITLE
nzbget: getting 'Permission denied' on /config/nzbget.conf

### ISSUE THREAD

**Issue by lknite** [k8s-at-home/charts#1469]
# Details

**Helm chart name and version:**

nzbget:latest

**What steps did you take and what happened:**

Installed helm chart via argocd.

```
$ k logs -f nzbget-6df9c5b46c-5ms5s 
cp: cannot create regular file '/config/nzbget.conf': Permission denied
sed: can't read /config/nzbget.conf: No such file or directory
nzbget.conf(0): Could not open file /config/nzbget.conf
```

**Relevant Helm values:**

```
nzbget:

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      tls:
      - hosts:
        - nzbget.<mydomain>
        secretName: nzbget.prod
      hosts:
      - host: nzbget.<mydomain>
        paths:
        - path: /
          pathType: Prefix
      annotations:
        cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
      readOnly: false
    downloads:
      enabled: true
      accessMode: ReadWriteOnce
      size: 20Gi
      readOnly: false
```

**What did you expect to happen:**

Working installation.

**Anything else you would like to add:**

I added 'readOnly: false' though that was expected to be set by default, didn't help.
