### ISSUE TITLE
pod-gateway ping to 8.8.8.8 unreachable and GATEWAY_IP connection timeout

### ISSUE THREAD

**Issue by chrisjohnson00** [k8s-at-home/charts#1503]
# Details

**Helm chart name and version:**

pod-gateway 5.2.1

**Container name and tag:**

ghcr.io/k8s-at-home/pod-gateway:v1.4.0
ghcr.io/k8s-at-home/gateway-admision-controller:v3.4.0

**What steps did you take and what happened:**

I followed the docs/guide, https://docs.k8s-at-home.com/guides/pod-gateway/, for setting up pod-gateway with some required updates for latest chart/container versions.  Here's my HelmRelease:

```
# HelmRelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: default
  labels:
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    routed_namespaces:
      - vpn
    image:
      tag: v1.4.0
    webhook:
      image:
        tag: v3.4.0
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.244.0.0/16"
```

When deploying the [test deployment](https://docs.k8s-at-home.com/guides/pod-gateway/#test-deployment), as is - no changes, I get the following

```
kubectl logs terminal-56487b4d9d-z2qt7 -c gateway-init -n vpn
+ cat /default_config/settings.sh
#!/bin/bash

# hostname of the gateway - it must accept vxlan and DHCP traffic
# clients get it as env variable
GATEWAY_NAME="$gateway"
# K8S DNS IP address
# clients get it as env variable
K8S_DNS_IPS="$K8S_DNS_ips"
# Blank  sepated IPs not sent to the POD gateway but to the default K8S
# This is needed, for example, in case your CNI does
# not add a non-default rule for the K8S addresses (Flannel does)
NOT_ROUTED_TO_GATEWAY_CIDRS=""

# Vxlan ID to use
VXLAN_ID="42"
# VXLAN need an /24 IP range not conflicting with K8S and local IP ranges
VXLAN_IP_NETWORK="172.16.0"
# Keep a range of IPs for static assignment in nat.conf
VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20

# If using a VPN, interface name created by it
VPN_INTERFACE=tun0
# Prevent non VPN traffic to leave the gateway
VPN_BLOCK_OTHER_TRAFFIC=true
# If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
VPN_TRAFFIC_PORT=443
# Traffic to these IPs will be send through the K8S gateway
VPN_LOCAL_CIDRS="10.0.0.0/8 192.168.0.0/16"

# DNS queries to these domains will be resolved by K8S DNS instead of
# the default (typcally the VPN client changes it)
DNS_LOCAL_CIDRS="local"

# dnsmasq monitors directories. /etc/resolv.conf in a container is in another
# file system so it does not work. To circumvent this a copy is made using
# inotifyd
RESOLV_CONF_COPY=/etc/resolv_copy.conf
+ . /default_config/settings.sh
++ GATEWAY_NAME=vpn-gateway-pod-gateway.default.svc.cluster.local
++ K8S_DNS_IPS=10.96.0.10
++ NOT_ROUTED_TO_GATEWAY_CIDRS=
++ VXLAN_ID=42
++ VXLAN_IP_NETWORK=172.16.0
++ VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20
++ VPN_INTERFACE=tun0
++ VPN_BLOCK_OTHER_TRAFFIC=true
++ VPN_TRAFFIC_PORT=443
++ VPN_LOCAL_CIDRS='10.0.0.0/8 192.168.0.0/16'
++ DNS_LOCAL_CIDRS=local
++ RESOLV_CONF_COPY=/etc/resolv_copy.conf
+ cat /config/settings.sh
#!/bin/sh
# Generated by vpn-gateway-pod-gateway
DNS_LOCAL_CIDRS="local"
NOT_ROUTED_TO_GATEWAY_CIDRS="10.244.0.0/16"
VPN_BLOCK_OTHER_TRAFFIC="false"
VPN_INTERFACE="tun0"
VPN_LOCAL_CIDRS="10.0.0.0/8 192.168.0.0/16"
VPN_TRAFFIC_PORT="443"
VXLAN_GATEWAY_FIRST_DYNAMIC_IP="20"
VXLAN_ID="42"
VXLAN_IP_NETWORK="172.16.0"
+ . /config/settings.sh
++ DNS_LOCAL_CIDRS=local
++ NOT_ROUTED_TO_GATEWAY_CIDRS=10.244.0.0/16
++ VPN_BLOCK_OTHER_TRAFFIC=false
++ VPN_INTERFACE=tun0
++ VPN_LOCAL_CIDRS='10.0.0.0/8 192.168.0.0/16'
++ VPN_TRAFFIC_PORT=443
++ VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20
++ VXLAN_ID=42
++ VXLAN_IP_NETWORK=172.16.0
+ ip addr
+ grep -q vxlan0
++ awk '/default/ { print $3 }'
++ /sbin/ip route
+ K8S_GW_IP=
+ for local_cidr in $NOT_ROUTED_TO_GATEWAY_CIDRS
+ ip route add 10.244.0.0/16 via ''
Error: inet address is expected rather than "".
+ /bin/true
+ echo 'Deleting existing default GWs'
+ ip route del 0/0
Deleting existing default GWs
RTNETLINK answers: No such process
+ /bin/true
+ ping -c 1 -W 1000 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network unreachable
+ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if77: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ae:cf:6a:cd:78:54 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.18/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever
+ ip route
10.244.0.0/24 dev eth0 proto kernel scope link src 10.244.0.18 
10.244.0.0/16 via 10.244.0.1 dev eth0 
++ cut -d ' ' -f 1
+ K8S_DNS_IP=10.96.0.10
++ dig +short vpn-gateway-pod-gateway.default.svc.cluster.local @10.96.0.10
+ GATEWAY_IP=';; connection timed out; no servers could be reached'
```

I'm using Flannel 0.17.0 on k8s 1.22 with a network CIDR of:
```
kubectl get cm kube-flannel-cfg -n kube-system -o yaml | grep Network
      "Network": "10.244.0.0/16",
```
Which you can see I've already set as the `NOT_ROUTED_TO_GATEWAY_CIDRS` value in the values.yaml in Flux.

**Relevant Helm values:**

From my HelmRelease:

```
  values:
    routed_namespaces:
      - vpn
    image:
      tag: v1.4.0
    webhook:
      image:
        tag: v3.4.0
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.244.0.0/16"
```

**Additional Information:**

From the gateway pod I performed these troubleshooting steps:

``` 
bash-5.1# ip route
default via 10.244.0.1 dev eth0 
10.0.0.0/8 via 10.244.0.1 dev eth0 
10.244.0.0/24 dev eth0 proto kernel scope link src 10.244.0.15 
10.244.0.0/16 via 10.244.0.1 dev eth0 
172.16.0.0/24 dev vxlan0 proto kernel scope link src 172.16.0.1 
192.168.0.0/16 via 10.244.0.1 dev eth0 
bash-5.1# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 96:b8:ce:7e:c5:38 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.15/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever
4: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 22:2c:8a:e1:cd:b9 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 scope global vxlan0
       valid_lft forever preferred_lft forever
bash-5.1# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
bash-5.1# ping -c1 example.com
PING example.com (93.184.216.34): 56 data bytes
64 bytes from 93.184.216.34: seq=0 ttl=54 time=15.946 ms

--- example.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 15.946/15.946/15.946 ms
```

I cannot execute any troubleshooting steps in the routed pod as the init container dies nearly instantly.
