### ISSUE TITLE
audiobooks chart persistence issues

### ISSUE THREAD

**Issue by putz612** [k8s-at-home/charts#1524]
# Details

**Helm chart name and version:**

audiobookshelf:1.0.0 

**Container name and tag:**

advplyr/audiobookshelf:1.6.69

**What steps did you take and what happened:**

I have been attempting to install the chart and use persistence for config however nothing I put in there seems to stick.  I have tried both normal pvc and using an existing claim. 

**Relevant Helm values:**

***Using existing claim***
```
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: audiobooks-config
    mountPath: /config
```
***Creating a PVC***
```
persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
```

**What did you expect to happen:**

A deployment would get created with persistence.  I have other charts in use that dynamically created PVC and existing PVC, this is the first one that has me stumped.
