### ISSUE TITLE
[adguard-home] externalTrafficPolicy is not set when using service with type NodePort

### ISSUE THREAD

**Issue by imstevenxyz** [k8s-at-home/charts#1537]
### Helm chart name

adguard-home

### Helm chart version

5.2.0

### Container name

adguard/adguard-home

### Container tag

v0.107.6

### Description

The values.yaml file provided for adguard-home includes by default two services with type NodePort and externalTrafficPolicy set to Local.

The common chart only includes externalTrafficPolicy if the type is set to LoadBalancer and will therefore not be applied.

### Expected result

That the externalTrafficPolicy is set as stated in the values file.

### Helm values to reproduce

```YAML
service:
    dns-tcp:
        enabled: true
        type: NodePort
        ports:
            dns-tcp:
                enabled: true
                port: 53
                protocol: TCP
                targetPort: 53
        externalTrafficPolicy: Local
    dns-udp:
        enabled: true
        type: NodePort
        ports:
            dns-udp:
                enabled: true
                port: 53
                protocol: UDP
                targetPort: 53
        externalTrafficPolicy: Local
```
