### ISSUE TITLE
[paperless] CSRF verification failed

### ISSUE THREAD

**Issue by djjudas21** [k8s-at-home/charts#1538]
### Helm chart name

paperless

### Helm chart version

8.6.2

### Container name

ghcr.io/paperless-ngx/paperless-ngx:ngx-1.7.0

### Container tag

ngx-1.7.0

### Description

When installing Paperless with Ingress enabled, I get `Your CSRF verification failed` when I try to browse to the app

### Expected result

I expect to be able to access the app via the Ingress

### Helm values to reproduce

```YAML
ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
    ingressClassName: "public"
    hosts:
      - host: paperless.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: paperless-tls
        hosts:
          - paperless.example.com
```

### Additional Information

This seems to be discussed upstream in https://github.com/paperless-ngx/paperless-ngx/issues/712

The solution is to set the environment variable `PAPERLESS_URL` to the same value as the Ingress host.

In my case, setting

```yaml
env:
  PAPERLESS_URL: https://paperless.example.com
```

made the app work via the Ingress as expected, so I think there should be at least a placeholder for `PAPERLESS_URL` in `values.yaml`. Even better would be the ability to automatically set `PAPERLESS_URL` to the same value as `ingress.main.hosts.host[0]`
