### ISSUE TITLE
[monica] SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by qiaouchicago** [k8s-at-home/charts#1542]
### Helm chart name

monica

### Helm chart version

7.1.0

### Container name

monica

### Container tag

3.7.0-apache

### Description

I connected to http address, got redirected to https with the same address.
Then firefox show the error message: 

```
Secure Connection Failed

An error occurred during a connection to k54l:30083. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```

### Expected result

I should be able to visit the site with http or https without any error.

### Helm values to reproduce

```YAML
env:
  TZ: "America/Chicago"
  DB_HOST: mariadb.default.svc.cluster.local
  DB_DATABASE: monica
  DB_USERNAME: monica
  DB_PASSWORD: monicapass
```
