### ISSUE TITLE
[common] Nodeselector and Tolerations don't render properly

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/charts#155]
When adding the following to the values:

```
nodeSelector:
  kubernetes.io/hostname: k8s-staticwan
tolerations:
- effect: NoSchedule
  operator: Exists
```

it gets rendered as:

```
nodeSelector:        kubernetes.io/hostname: k8s-staticwan
tolerations:        - effect: NoSchedule
  operator: Exists
```

Gotta fix that indenting 😮
