### ISSUE TITLE
[question] additionalVolumeMounts usage

### ISSUE THREAD

**Issue by BungeBash** [k8s-at-home/charts#158]
Seems like using additional mounts behavior has changed from the original use case on things like ombi/sonarr/etc.  Can someone add description (or potentially fix) additionalVolumeMounts?  

Previous method:
```
persistence: 
  extraExistingClaimMounts:
      - name: "downloads"
        mountPath: "/downloads"
        existingClaim: "downloads"
        readOnly: false
```

New method:
```
persistence:
  additionalVolumeMounts:
     - name: "downloads"
       mountPath: "/downloads"
       existingClaim: "downloads"
       readOnly: false
```

That results in:
`Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[1]): unknown field "existingClaim" in io.k8s.api.core.v1.VolumeMount`

Removing the existingClaim results in the mount not being found.  I'm sure I have poor formatting but this is not my expertise.

**Comment by onedr0p** [comment]
Hi @BungeBash sorry for the confusion on the chart updates but yes, additionalVolumes have changed

Here's a snippet from my https://github.com/onedr0p/home-cluster/blob/main/cluster/media/sonarr.yaml#L19 deployment:

```yaml
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "25Gi"
    additionalVolumeMounts:
    - name: media-rocinante
      mountPath: "/media-rocinante"
    - name: media-serenity
      mountPath: "/media-serenity"
    additionalVolumes:
    - name: media-rocinante
      persistentVolumeClaim:
        claimName: nfs-media-rocinante-pvc
    - name: media-serenity
      persistentVolumeClaim:
        claimName: nfs-media-serenity-pvc
```
