### ISSUE TITLE
[vaultwarden] Ingress fails to deploy with example from values.yaml

### ISSUE THREAD

**Issue by rlex** [k8s-at-home/charts#1585]
### Helm chart name

vaultwarden

### Helm chart version

4.2.3

### Container name

vaultwarden/server

### Container tag

1.25.0

### Description

When installing with example from values.yaml for ingress, notably paths part: https://github.com/k8s-at-home/charts/blob/master/charts/stable/vaultwarden/values.yaml#L44-L56

Install fails with following error:
```
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer", ValidationError(Ingress.spec.rules[0].http.paths[1].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer", ValidationError(Ingress.spec.rules[0].http.paths[2].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"]
```

Replacing port names with numbers fixes issue:
```yaml
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      port: 80
                  - path: /notifications/hub/negotiate
                    pathType: Prefix
                    service:
                      port: 80
                  - path: /notifications/hub
                    pathType: Prefix
                    service:
                      port: 3012
```

### Expected result

Ingress should be deployed without errors

### Helm values to reproduce

```YAML
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
          - path: /notifications/hub/negotiate
            pathType: Prefix
            service:
              port: http
          - path: /notifications/hub
            pathType: Prefix
            service:
              port: websocket
```
