### ISSUE TITLE
[pod-gateway] Crash running initContainer for pod using non-default user

### ISSUE THREAD

**Issue by zebrapurring** [k8s-at-home/charts#1590]
### Helm chart name

pod-gateway

### Helm chart version

5.4.2

### Container name

ghcr.io/k8s-at-home/pod-gateway

### Container tag

v1.5.0

### Description

The init container injected into client pods crashes if the target pod uses a non-standard UID.

For example, running `gitlab-runner` which configures the security context as follows:

```yaml
securityContext:
  runAsUser: 999
  fsGroup: 999
```

Results in the following error log from the `gateway-init` container in `gitlab-runner` pod:

<details>
  <summary><code>gateway-init</code> container logs</summary>

  ```
  + cat /default_config/settings.sh
  #!/bin/bash

  # hostname of the gateway - it must accept vxlan and DHCP traffic
  # clients get it as env variable
  GATEWAY_NAME="$gateway"
  # K8S DNS IP address
  # clients get it as env variable
  K8S_DNS_IPS="$K8S_DNS_ips"
  # Blank  sepated IPs not sent to the POD gateway but to the default K8S
  # This is needed, for example, in case your CNI does
  # not add a non-default rule for the K8S addresses (Flannel does)
  NOT_ROUTED_TO_GATEWAY_CIDRS=""

  # Vxlan ID to use
  VXLAN_ID="42"
  # VXLAN need an /24 IP range not conflicting with K8S and local IP ranges
  VXLAN_IP_NETWORK="172.16.0"
  # Keep a range of IPs for static assignment in nat.conf
  VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20

  # If using a VPN, interface name created by it
  VPN_INTERFACE=tun0
  # Prevent non VPN traffic to leave the gateway
  VPN_BLOCK_OTHER_TRAFFIC=true
  # If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
  VPN_TRAFFIC_PORT=443
  # Traffic to these IPs will be send through the K8S gateway
  VPN_LOCAL_CIDRS="10.0.0.0/8 192.168.0.0/16"

  # DNS queries to these domains will be resolved by K8S DNS instead of
  # the default (typcally the VPN client changes it)
  DNS_LOCAL_CIDRS="local"

  # dnsmasq monitors directories. /etc/resolv.conf in a container is in another
  # file system so it does not work. To circumvent this a copy is made using
  # inotifyd
  RESOLV_CONF_COPY=/etc/resolv_copy.conf
  + . /default_config/settings.sh
  ++ GATEWAY_NAME=vpn-gateway-pod-gateway.vpn-gateway.svc.cluster.local
  ++ K8S_DNS_IPS=10.43.0.10
  ++ NOT_ROUTED_TO_GATEWAY_CIDRS=
  ++ VXLAN_ID=42
  ++ VXLAN_IP_NETWORK=172.16.0
  ++ VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20
  ++ VPN_INTERFACE=tun0
  ++ VPN_BLOCK_OTHER_TRAFFIC=true
  ++ VPN_TRAFFIC_PORT=443
  ++ VPN_LOCAL_CIDRS='10.0.0.0/8 192.168.0.0/16'
  ++ DNS_LOCAL_CIDRS=local
  ++ RESOLV_CONF_COPY=/etc/resolv_copy.conf
  + cat /config/settings.sh
  #!/bin/sh
  # Generated by vpn-gateway-pod-gateway
  DNS_LOCAL_CIDRS="local"
  NOT_ROUTED_TO_GATEWAY_CIDRS="10.0.0.0/8"
  VPN_BLOCK_OTHER_TRAFFIC="false"
  VPN_INTERFACE="wg0"
  VPN_LOCAL_CIDRS="10.0.0.0/8"
  VPN_TRAFFIC_PORT="51820"
  VXLAN_GATEWAY_FIRST_DYNAMIC_IP="20"
  VXLAN_ID="42"
  VXLAN_IP_NETWORK="172.16.0"
  + . /config/settings.sh
  ++ DNS_LOCAL_CIDRS=local
  ++ NOT_ROUTED_TO_GATEWAY_CIDRS=10.0.0.0/8
  ++ VPN_BLOCK_OTHER_TRAFFIC=false
  ++ VPN_INTERFACE=wg0
  ++ VPN_LOCAL_CIDRS=10.0.0.0/8
  ++ VPN_TRAFFIC_PORT=51820
  ++ VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20
  ++ VXLAN_ID=42
  ++ VXLAN_IP_NETWORK=172.16.0
  + ip addr
  + grep -q vxlan0
  ++ /sbin/ip route
  ++ awk '/default/ { print $3 }'
  + K8S_GW_IP=10.42.0.1
  + for local_cidr in $NOT_ROUTED_TO_GATEWAY_CIDRS
  + ip route add 10.0.0.0/8 via 10.42.0.1
  RTNETLINK answers: Operation not permitted
  + /bin/true
  + echo 'Deleting existing default GWs'
  + ip route del 0/0
  RTNETLINK answers: Operation not permitted
  + /bin/true
  Deleting existing default GWs
  + ping -c 1 -W 1000 8.8.8.8
  PING 8.8.8.8 (8.8.8.8): 56 data bytes
  ping: permission denied (are you root?)
  + ip addr
  + ip route
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host 
         valid_lft forever preferred_lft forever
  2: eth0@if29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8950 qdisc noqueue state UP group default 
      link/ether 46:56:2e:74:70:54 brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet 10.42.0.26/24 brd 10.42.0.255 scope global eth0
         valid_lft forever preferred_lft forever
      inet6 fe80::4456:2eff:fe74:7054/64 scope link 
         valid_lft forever preferred_lft forever
  default via 10.42.0.1 dev eth0 
  10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.26 
  10.42.0.0/16 via 10.42.0.1 dev eth0 
  ++ cut -d ' ' -f 1
  + K8S_DNS_IP=10.43.0.10
  ++ dig +short vpn-gateway-pod-gateway.vpn-gateway.svc.cluster.local @10.43.0.10
  + GATEWAY_IP=10.42.1.30
  +++ hostname
  ++ grep gitlab-runner-675f9fbd87-kklzm /config/nat.conf
  ++ true
  + NAT_ENTRY=
  + VXLAN_GATEWAY_IP=172.16.0.1
  + ip addr
  + ip route
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host 
         valid_lft forever preferred_lft forever
  2: eth0@if29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8950 qdisc noqueue state UP group default 
      link/ether 46:56:2e:74:70:54 brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet 10.42.0.26/24 brd 10.42.0.255 scope global eth0
         valid_lft forever preferred_lft forever
      inet6 fe80::4456:2eff:fe74:7054/64 scope link 
         valid_lft forever preferred_lft forever
  default via 10.42.0.1 dev eth0 
  10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.26 
  10.42.0.0/16 via 10.42.0.1 dev eth0 
  + ping -c1 10.42.1.30
  ping: permission denied (are you root?)
  PING 10.42.1.30 (10.42.1.30): 56 data bytes
  ```
</details>

### Expected result

The init container should run as the required user by its own script and complete successfully.

### Helm values to reproduce

```YAML
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/pod-gateway/values.yaml
  values:
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository of the gateway and inserted helper containers
      repository: ghcr.io/k8s-at-home/pod-gateway
      # -- image pull policy of the gateway and inserted helper cotainers
      pullPolicy: IfNotPresent
      # -- image tag of the gateway and inserted helper containers
      tag: v1.5.0

    # -- IP address of the DNS server within the vxlan tunnel.
    # All mutated PODs will get this as their DNS server.
    # It must match VXLAN_GATEWAY_IP in settings.sh
    DNS: 192.168.1.1

    # -- The DNSPolicy to apply to the POD. Only when set to "None" will the
    # DNS value above apply. To avoid altering POD DNS (i.e., to allow
    # initContainers to use DNS before the the VXLAN is up), set to "ClusterFirst"
    DNSPolicy: None

    # -- cluster name used to derive the gateway full name
    clusterName: cluster.local

    # -- Namespaces that might contain routed PODs and therefore
    # require a copy of the generated settings configmap.
    routed_namespaces:
      - gitlab

    settings:
      # -- IPs not sent to the POD gateway but to the default K8S.
      # Multiple CIDRs can be specified using blanks as separator.
      # Example for Calico: ""172.22.0.0/16 172.24.0.0/16"
      #
      # This is needed, for example, in case your CNI does
      # not add a non-default rule for the K8S addresses (Flannel does).
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8

      # -- Vxlan ID to use
      VXLAN_ID: 42
      # -- VXLAN needs an /24 IP range not conflicting with K8S and local IP ranges
      VXLAN_IP_NETWORK: 172.16.0
      # -- Keep a range of IPs for static assignment in nat.conf
      VXLAN_GATEWAY_FIRST_DYNAMIC_IP: 20

      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: false
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: 51820
      # -- Traffic to these IPs will be sent through the K8S gateway
      VPN_LOCAL_CIDRS: 10.0.0.0/8

      # -- DNS queries to these domains will be resolved by K8S DNS instead of
      # the default (typcally the VPN client changes it)
      DNS_LOCAL_CIDRS: local

    addons:
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
                - sysctl net.ipv4.conf.all.src_valid_mark=1
        env:
          TZ: ${CLUSTER_TZ}
          IPTABLES_BACKEND: legacy # nft
          KILLSWITCH: false
        configFileSecret: wireguard-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        nodeSelector:
          worker: yes
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - if curl -s my.internal.domain; then exit 0; else exit $?; fi
          initialDelaySeconds: 45
          periodSeconds: 120
          failureThreshold: 1
        networkPolicy:
          enabled: true
          egress:
            # Allow all traffic
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0

    # -- The webhook is used to mutate the PODs matching the given
    # namespace labels. It inserts an init and sidecard helper containers
    # that connect to the gateway pod created by this chart.
    # @default -- See below
    webhook:
      image:
        # -- image repository of the webhook
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        # -- image pullPolicy of the webhook
        pullPolicy: IfNotPresent
        # -- image tag of the webhook
        tag: v3.4.0

      # -- number of webhook instances to deploy
      replicas: 1

      # -- strategy for updates
      strategy:
        type: RollingUpdate

      # -- Selector for namespace.
      # All pods in this namespace will get evaluated by the webhook.
      # **IMPORTANT**: Do not select the namespace where the webhook
      # is deployed to or you will get locking issues.
      namespaceSelector:
        type: label
        label: vpn-routed-ns

      # -- default behviour for new PODs in the evaluated namespace
      gatewayDefault: true

      # -- label name to check when evaluating POD. If true the POD
      # will get the gateway. If not set setGatewayDefault will apply.
      gatewayLabel: setGateway

      # -- annotation name to check when evaluating POD. If true the POD
      # will get the gateway. If not set setGatewayDefault will apply.
      gatewayAnnotation: setGateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    vpn-routed-ns: "true"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.41.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image: gitlab/gitlab-runner:ubuntu-v14.6.0
    
    imagePullSecrets: 
      - name: regcred

    nameOverride: gitlab-runner
    gitlabUrl: https://my.gitlab.server
    certsSecretName: gitlab-tls-certs
    concurrent: 10
    checkInterval: 30
    rbac:
      create: true
    env:
      TZ: Europe/Berlin
    runners:
      # runner configuration, where the multi line strings is evaluated as
      # template so you can specify helm values inside of it.
      #
      # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
      # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
      secret: gitlab-runner-secret
      imagePullSecrets: 
        - name: regcred
        - name: gitlabcred
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:20.04"
            [runners.cache]
              Type = "s3"
              Path = "runner"
              Shared = true
    hpa: 
      minReplicas: 1
      maxReplicas: 10
      metrics:
      - type: Pods
        pods:
          metricName: gitlab_runner_jobs
          targetAverageValue: 400m
    securityContext:
      runAsUser: 999
      fsGroup: 999
    resources:
      requests:
        cpu: 1000m
        memory: 1280M
```
