### ISSUE TITLE
[vikunja] Configuration may contain secrets, stored as configmap

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/charts#1596]
### Helm chart name

vikunja

### Helm chart version

5.5.3

### Container name

vikunja/api

### Container tag

0.17.1

### Description

Vikunja configuration can contain several secrets (JWT, OpenID secrets, etc) but is stored as a ConfigMap.

Most settings can be sourced from the environment instead, but not the authentication configuration.

### Expected result

Secret values should be in secrets

### Helm values to reproduce

```YAML
vikunja:
  config: |-
    auth:
      openid:
        providers:
          - name: Foo
            clientsecret: secret-is-in-the-name
```
