### ISSUE TITLE
[owncast] Cannot set Service type to `ClusterIP` for `owncast-rtmp` and provide an `externalTrafficPolicy`

### ISSUE THREAD

**Issue by Matthew-Beckett** [k8s-at-home/charts#1676]
### Helm chart name

owncast

### Helm chart version

3.3.2

### Container name

gabekangas/owncast

### Container tag

latest

### Description

When deploying Owncast with the `rtmp` service deployed on a ClusterIP Service instead of the provided LoadBalancer service type deployment will fail as there is guard rails in the chart for checking the value of `externalTrafficPolicy`.

When providing an `externalTrafficPolicy` of `Cluster` the following output is returned:

```
Service "owncast-rtmp" is invalid: spec.externalTrafficPolicy: Invalid value: "Cluster": may only be set when `type` is 'NodePort' or 'LoadBalancer'
```

and when providing an `externalTrafficPolicy` of `Local` the following output is returned:

```
reconciliation failed: Helm upgrade failed: failed to create resource: Service "owncast-rtmp" is invalid: spec.externalTrafficPolicy: Invalid value: "Local": may only be set when `type` is 'NodePort' or 'LoadBalancer'
```

I also could not set it to nil.

### Expected result

I should be able to provide an externalTrafficPolicy of `Local` or `Cluster` depending on my use case.

### Helm values to reproduce

```YAML
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: owncast
spec:
  interval: 1h0m0s
  url: https://k8s-at-home.com/charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: owncast
  labels:
    app: owncast
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owncast
  namespace: owncast
spec:
  chart:
    spec:
      chart: owncast
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    image:
      tag: latest
    service:
      rtmp:
        type: ClusterIP
        externalTrafficPolicy: Cluster
```
