### ISSUE TITLE
[tt-rss] env valueFrom doesn't work

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/charts#1685]
### Helm chart name

tt-rss

### Helm chart version

5.0.0

### Container name

tt-rss

### Container tag

default

### Description

The library chart [defines](https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml#L107=) multiple ways of populating env vars, including `valueFrom`. The tt-rss [template](https://github.com/k8s-at-home/charts/blob/81ca3d5d0698705fa23e0fae1bbcf1016d0bca91/charts/stable/tt-rss/templates/common.yaml#L13) breaks that by comparing it to ""

### Expected result

Env vars are linked to secrets, configmaps, etc as is possible with the other kah charts.

### Helm values to reproduce

```YAML
env:
  TTRSS_DB_PASS:
    valueFrom:
      secretKeyRef:
        name: ttrss-postgresql-secret
        key: postgresql-password
```

### Additional Information

```
Helm install failed: template: tt-rss/templates/common.yaml:13:7: executing "tt-rss/templates/common.yaml" at <eq .Values.env.TTRSS_DB_PASS "">: error calling eq: uncomparable type map[string]interface {}: map[valueFrom:map[secretKeyRef:map[key:postgresql-password name:ttrss-postgresql-secret]]] Last Helm logs:
```
