### ISSUE TITLE
[pod-gateway] Unable to ping lan gateway from pod-gateway

### ISSUE THREAD

**Issue by ameyp** [k8s-at-home/charts#1699]
### Helm chart name

pod-gateway

### Helm chart version

latest

### Container name

pod-gateway

### Container tag

v1.6.0

### Description

I'm unable to my LAN (actually a VLAN, but don't think that's relevant) gateway IP `192.168.80.1` from the `pod-gateway` container.

Here's the output of `ip route`:
```
default via 10.42.5.1 dev eth0 
10.0.0.0/8 via 10.42.5.1 dev eth0 
10.42.0.0/16 via 10.42.5.1 dev eth0 
10.42.5.0/24 dev eth0 proto kernel scope link src 10.42.5.30 
172.16.0.0/24 dev vxlan0 proto kernel scope link src 172.16.0.1 
192.168.0.0/16 via 10.42.5.1 dev eth0 
```

Here's the output of `ip addr`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ea:8a:02:9b:8e:68 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.5.30/24 brd 10.42.5.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e88a:2ff:fe9b:8e68/64 scope link 
       valid_lft forever preferred_lft forever
3: vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether aa:17:36:28:09:d6 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 scope global vxlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::a817:36ff:fe28:9d6/64 scope link 
       valid_lft forever preferred_lft forever
```

And here's the output of ping:

```
bash-5.1# ping 192.168.80.1
PING 192.168.80.1 (192.168.80.1): 56 data bytes
^C
--- 192.168.80.1 ping statistics ---
9 packets transmitted, 0 packets received, 100% packet loss
```

Please let me know if there's any other config I can provide.

### Expected result

I'm able to ping the LAN gateway IP from the pod-gateway pod

### Helm values to reproduce

```YAML
image:
  tag: v1.6.0

routed_namespaces:
  - vpn-test

addons:
  vpn:
    enabled: true
    type: openvpn
    openvpn:
      auth: "email@proton.me;password"
    configFileSecret: openvpn
    networkPolicy:
      enabled: true

      egress:
        - to:
          - ipBlock:
              cidr: 0.0.0.0/0
          ports:
            # VPN traffic port - change if your provider uses a different port
          - port: 443
            protocol: UDP
        - to:
            # Allow traffic within K8S - change if your K8S cluster uses a different CIDR
          - ipBlock:
              cidr: 10.0.0.0/8

settings:
  # tun0 for openvpn, wg0 for wireguard
  VPN_INTERFACE: tun0
  # Prevent non VPN traffic to leave the gateway
  VPN_BLOCK_OTHER_TRAFFIC: true
  # If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
  VPN_TRAFFIC_PORT: 443
  # Traffic to these IPs will be send through the K8S gateway
  # change if your K8S cluster or home network uses a different CIDR
  VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
```

### Additional Information

I'm installing the chart with:

```
helm upgrade --install pod-gateway k8s-at-home/pod-gateway -n vpn-gateway -f gateway.yaml --create-namespace
```
