### ISSUE TITLE
[Bookstack] smtp.gmail.com unable to resolve as email host

### ISSUE THREAD

**Issue by mike12806** [k8s-at-home/charts#1708]
### Helm chart name

Bookstack

### Helm chart version

5.0.0.0

### Container name

ghcr.io/linuxserver/bookstack:version-v21.12

### Container tag

v21.12

### Description

When trying to send a test email, I get the following error:

`Error thrown when sending a test email: Connection could not be established with host smtp.gmail.com :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name does not resolve`

### Expected result

After seeing the following variables (below) and deploying this helm chart, I would expect Bookstack to be able to resolve the email host smtp.gmail.com

### Helm values to reproduce

```YAML
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_ENCRYPTION: tls
  MAIL_USERNAME: [REDACTED]
  MAIL_PASSWORD: [REDACTED]
  MAIL_FROM: [REDACTED]
  MAIL_FROM_NAME: BookStack
```

### Additional Information

Running inside a K3s cluster w/ Rancher. Both Bookstack and MariaDB are using LoadBalancerIP address.
