### ISSUE TITLE
[mosquitto] version 4.8.1 is breaking

### ISSUE THREAD

**Issue by morremeyer** [k8s-at-home/charts#1730]
### Helm chart name

mosquitto

### Helm chart version

4.8.1

### Container name

eclipse-mosquitto

### Container tag

irrelevant

### Description

Upgrading from version 4.7.1 to 4.8.1 or 4.8.2 is not possible without updating configuration, making this a breaking change - 4.8.1 should therefore have been released as 5.0.0.

### Expected result

Minor version is not including breaking changes.

For breaking changes, the changelog should contain migration instructions.

### Helm values to reproduce

```YAML
auth:
  enabled: true

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi

  # This is only enabled for the line in the config file
  # No data is stored inside. Check home-assistant/mosquitto-config instead
  configinc:
    enabled: true

  passwd:
    enabled: true
    type: custom
    readOnly: true
    mountPath: /mosquitto/config/passwd
    subPath: passwd
    volumeSpec:
      configMap:
        name: mosquitto-additional-config

  additional-config:
    enabled: true
    type: custom
    readOnly: true
    mountPath: /mosquitto/configinc/mosquitto-additional.conf
    subPath: mosquitto-additional.conf
    volumeSpec:
      configMap:
        name: mosquitto-additional-config
```
```


### Additional Information

I initially assumed this is due to my configuration, but it occurs as soon as `persistence.configinc.enabled` is set to true.

I'll be submitting a bugfix with a sensible default in a moment.

### Repo link

_No response_
