### ISSUE TITLE
[bookstack] MariaDB fails to cold start (allegedly due its lack of rootPassword default)

### ISSUE THREAD

**Issue by alexbarcelo** [k8s-at-home/charts#1733]
### Helm chart name

bookstack

### Helm chart version

5.0.0

### Container name

docker.io/bitnami/mariadb

### Container tag

10.6.8-debian-11-r9

### Description

I used mostly default values, with the honorable mention of persistent storage for MariaDB.

### Expected result

A cold start / dirty restart of the cluster should not break the bookstack web app.

### Helm values to reproduce

```YAML
mariadb:
  enabled: true
  primary:
    persistence:
      enabled: true
```

### Additional Information

The pod for MariaDB seems to start properly, but it quickly fails with the error `Access denied for user 'root'@'localhost'`
