### ISSUE TITLE
[anonaddy] Update the documentation

### ISSUE THREAD

**Issue by Stoffe** [k8s-at-home/charts#1750]
### Helm chart name

anonaddy

### Helm chart version

latest

### Container name

anonaddy

### Container tag

latest

### Description

Pls update the documentation of the chart, the SECRET needs to be a hashed value (for instance, run the command shown below in the APP_KEY value again, if you just put a random string here, it will fail to start the webserver with a php error telling you its an unsupported format, but since it does not tell you what it is that is an unsupported format and the docs dont say much either, it took some time to investigate.
These docs needs more to be complete, many things are left out, pls try to install it yourself and update the docs accordingly.
If you are updating the docs only from the upstream repo, I can send a request there as well.

### Expected result

Docs would tell me what is required and what is not when it comes to the variables in the helm chart.

### Helm values to reproduce

```YAML
env:
  TZ: "Europe/Stockholm"
  ANONADDY_DOMAIN: *******
  ANONADDY_SECRET: base64:********** <- THIS NEEDS TO BE A PROPER SECRET, not a random string!
  ANONADDY_ADMIN_USERNAME: *****
```

### Repo link

https://github.com/anonaddy/anonaddy
https://github.com/k8s-at-home/charts/tree/master/charts/stable/anonaddy
