### ISSUE TITLE
[<chart name>] Concise description of the issue

### ISSUE THREAD

**Issue by fabricesemti80** [k8s-at-home/charts#1757]
### Helm chart name

qbittorrent-vpn

### Helm chart version

13.5.2

### Container name

ghcr.io/k8s-at-home/qbittorrent

### Container tag

v4.4.3.1

### Description

The app creates, but qbit shows error upon torrent  (file error / permission denied)

 -I use NFS backend
- went into the pod as exec, and can write files into `/media/downloads`
- did the same from another pod - also worked
- my settings: [helmrelease](https://github.com/fabricesemti80/home-stack/blob/main/cluster/apps/media/qbittorrent-vpn/helm-release.yaml)

### Expected result

qbit should be able to save files

### Helm values to reproduce

```YAML
values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.3.1
    updateStrategy: Recreate
    env:
      TZ: "${TIMEZONE}"

   # service:
   #   main:
   #     ports:
   #       http:
   #         port: 8080

      # bittorrent:
      #   enabled: true
      #   type: LoadBalancer
      #   externalIPs:
      #     - "${SVC_QBITTORRENT_ADDR}"
      #   ports:
      #     bittorrent:
      #       enabled: true
      #       port: ${VPN_PORT_QB}
      #       protocol: TCP
      #       targetPort: ${VPN_PORT_QB}
      #   externalTrafficPolicy: Local

    # ^ Ingress(es) configuration
    ingress:

      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
        hosts:
          - host: "qb-vpn.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qb-vpn.${SECRET_DOMAIN}"
            secretName: "qb-vpn-tls"

    # ^ Additional settings
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-vpn-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_SERVER}"
            path: "${NAS_PATH_MEDIA}"
        mountPath: /media
    # podAnnotations:
    #   setGateway: "true"

      # backup.velero.io/backup-volumes: config
      # pre.hook.backup.velero.io/on-error: continue
      # pre.hook.backup.velero.io/container: fsfreeze
      # pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/config"]'
      # post.hook.backup.velero.io/container: fsfreeze
      # post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/config"]'

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi

# or please see link in description
```

### Repo link

https://github.com/fabricesemti80/home-stack
