### ISSUE TITLE
[dendrite] clientapi.config.registration_disabled always returns to true

### ISSUE THREAD

**Issue by samip5** [k8s-at-home/charts#1759]
### Helm chart name

dendrite

### Helm chart version

6.3.0

### Container name

ghcr.io/matrix-org/dendrite-monolith

### Container tag

v0.9.3

### Description

It seems that no matter what, the `clientapi.config.registration_disabled: false` will not come into effect.

### Expected result

I expected it to get templated correctly.

### Helm values to reproduce

```YAML
image:
  repository: ghcr.io/matrix-org/dendrite-monolith
  tag: v0.9.3
  pullPolicy: IfNotPresent
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: zerossl-production
      external-dns.home.arpa/enabled: "true"
    hosts:
      - host: d.k8s-at-home.com
        paths:
          - path: /
            pathType: Prefix
          - path: /.well-known/matrix/server
            pathType: Prefix
          - path: /.well-known/matrix/client
            pathType: Prefix
      - host: k8s-at-home.com
        paths:
          - path: /.well-known/matrix/
            pathType: Prefix
          - path: /.well-known/matrix/server
            pathType: Prefix
          - path: /.well-known/matrix/client
            pathType: Prefix
    tls:
      - secretName: dendrite-cert
        hosts:
          - d.k8s-at-home.com
persistence:
  media:
    enabled: true
    existingClaim: dendrite-media-pvc
  jetstream:
    enabled: true
    existingClaim: dendrite-jetstream-pvc
dendrite:
  polylithEnabled: false
  matrix_key_secret:
    existingSecret: dendrite-matrix-key
  global:
    server_name: k8s-at-home.com
    well_known_server_name: d.k8s-at-home.com:443
    well_known_client_name: https://d.k8s-at-home.com:443
    mscs:
      - msc2946
      - msc2444
    presence:
      enable_outbound: true
      enable_inbound: true
    database:
      connection_string: ${CONNECTION_STRING}
clientapi:
  config:
    registration_disabled: false
podAnnotations:
  secret.reloader.stakater.com/reload: "dendrite-config"
postgresql:
  enabled: false
```

### Repo link

https://github.com/samip5/k8s-cluster/blob/98900661842018aec51a04213e0e561054520477/cluster/apps/default/dendrite/helm-release.yaml
