### ISSUE TITLE
[plex] unable to attach or mount volumes

### ISSUE THREAD

**Issue by razagill** [k8s-at-home/charts#18]
I'm new to kubernetes so I'm not sure if this is expected or not. I'm trying to add the `plex` chart to my cluster and I have only a single PV and PVC. After starting the chart it's stuck at `ContainerCreating` because it cannot attach the volumes
```bash
Unable to attach or mount volumes: unmounted volumes=[data transcode], unattached volumes=[data config transcode shared default-token-8s7wb]: timed out waiting for the condition
```

It seems to me that it might be because `deployment.yml` file storing hardcoded values for `volumeMounts` as they don't exist in my cluster. e.g. https://github.com/billimek/billimek-charts/blob/master/charts/plex/templates/deployment.yaml#L196

Is there a reason we are hardcoding those values, do I need to setup extra PVC named as they are?

There is a similar issue [here](https://github.com/munnerz/kube-plex/issues/103) which seems to have the same problem.

Here is the `kubectl describe pod ...`
```yaml
Name:           plex-69fb48c94f-tf56c
Namespace:      media
Priority:       0
Node:           mona-2/192.168.0.224
Start Time:     Tue, 18 Aug 2020 20:57:35 +0200
Labels:         app.kubernetes.io/instance=plex
                app.kubernetes.io/name=plex
                pod-template-hash=69fb48c94f
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/plex-69fb48c94f
Containers:
  plex:
    Container ID:   
    Image:          plexinc/pms-docker:1.19.1.2645-ccb6eb67e
    Image ID:       
    Ports:          32400/TCP, 32469/TCP, 1900/UDP, 32410/UDP, 32412/UDP, 32413/UDP, 32414/UDP
    Host Ports:     0/TCP, 0/TCP, 0/UDP, 0/UDP, 0/UDP, 0/UDP, 0/UDP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:32400/identity delay=15s timeout=5s period=10s #success=1 #failure=5
    Readiness:      http-get http://:32400/identity delay=15s timeout=5s period=10s #success=1 #failure=5
    Environment:
      TZ:                    Europe/London
      PLEX_CLAIM:            REDACTED
      PMS_INTERNAL_ADDRESS:  http://plex:32400
      PMS_IMAGE:             plexinc/pms-docker:1.19.1.2645-ccb6eb67e
      KUBE_NAMESPACE:        media (v1:metadata.namespace)
      TRANSCODE_PVC:         media-ssd
      DATA_PVC:              media-ssd
      CONFIG_PVC:            media-ssd
      PLEX_UID:              1000
      PLEX_GID:              1000
    Mounts:
      /config from config (rw)
      /data from data (rw)
      /shared from shared (rw)
      /transcode from transcode (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8s7wb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  media-ssd
    ReadOnly:   false
  config:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  media-ssd
    ReadOnly:   false
  transcode:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  media-ssd
    ReadOnly:   false
  shared:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-8s7wb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8s7wb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    <unknown>            default-scheduler  Successfully assigned media/plex-69fb48c94f-tf56c to hydra-2
  Warning  FailedMount  22m (x3 over 35m)    kubelet, hydra-2   Unable to attach or mount volumes: unmounted volumes=[data transcode], unattached volumes=[shared default-token-8s7wb data config transcode]: timed out waiting for the condition
```
