### ISSUE TITLE
[home-assistant] included esphome fails to start on multi-node clusters

### ISSUE THREAD

**Issue by cryptk** [k8s-at-home/charts#19]
Hello,

I have a 4 node RPi K3S cluster and I'm running your chart for home-assistant.  When setting `esphome.enabled: true` by default it tries to mount in the home-assistant pvc so that it can access the home-assistant secrets.yaml.  This does not work if the esphome pod is scheduled on a node where the home-assistant pvc does not exist.

I was able to work around this with the following settings to the home-assistant values:

```
esphome:
  enabled: true
  extraVolumes: null
  extraVolumeMounts: null
```

If you decide to keep this cross-mounting behavior in the home-assistant chart, you should add an affinity rule when esphome is enabled as well so that the pods will both co-locate.  I think that ideally the secrets.yaml would be provided via a kubernetes secret which would allow the file to be mounted into both containers with no affinity concerns.

**Comment by carpenike** [comment]
It would be interesting to find a way to mount the Kube secret as secrets.yaml in a place that hass will recognize it.

**Comment by carpenike** [comment]
@bjw-s -- do you think we could leverage some of the secrets work we were discussing for Hass here too?

**Comment by bjw-s** [comment]
By the looks of it you could manage the secrets file from a Kubernetes Secret with something like the following values in `values.yaml`. You would have a small bit of duplication in the values file though:

```yaml
esphome:
  extraVolumes:
    - name: hass-secrets
      secret:
        secretName: <pre-existing secret name goes here>
  extraVolumeMounts:
     - name: hass-secrets
       mountPath: /config/secrets.yaml
       subPath: secrets.yaml

extraVolumes:
  - name: hass-secrets
    secret:
      secretName: <pre-existing secret name goes here>

extraVolumeMounts:
   - name: hass-secrets
     mountPath: /config/secrets.yaml
     subPath: secrets.yaml
```
