### ISSUE TITLE
[calibre-web] Pod does does terminate with [s6-finish] sending all processes the TERM signal.

### ISSUE THREAD

**Issue by papanito** [k8s-at-home/charts#28]
I install the chart with the default values but the pod constantly restarts. It comes up but after `[s6-finish] waiting for services.` the pod does a `[s6-finish] sending all processes the TERM signal.`.

```
kubectl -n calibre logs calibre-calibre-web-58c874b9d8-5fssm calibre-web -f
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Thus `web-test-connection` always fails

```
kubectl -n calibre logs calibre-calibre-web-test-connection
Connecting to calibre-calibre-web:8083 (10.43.52.188:8083)
```

**Comment by WojoInc** [comment]
Could you provide your values.yaml?
My thought here is that the pod may be taking to long to bring up the webui. 
I say this as there are other steps that should run after 30-config.

Typically I have seen this run slow on certain types of persistent volumes. (Namely NFS)
As a quick test, have you tried increasing initialDelaySeconds for both the readiness and liveness probes? 
Also, I would try disabling persistence and seeing if the pod initializes properly.

**Comment by papanito** [comment]
```
image:
  repository: linuxserver/calibre-web
  tag: 0.6.8-ls74
  pullPolicy: IfNotPresent

strategyType: Recreate

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10

nameOverride: ""
fullnameOverride: ""

dockerMods:
  ebookConversion:
    enabled: false
    image:
      repository: linuxserver/calibre-web
      tag: calibre

timezone: UTC
puid: 1001
pgid: 1001
umask: 22

service:
  type: ClusterIP
  port: 8083
  annotations: {}
  labels: {}

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
  books:
    enabled: true
    accessMode: ReadWriteOnce
    size: 15Gi
    skipuninstall: false
  extraExistingClaimMounts: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
deploymentAnnotations: {}
```
