### ISSUE TITLE
templates/common.yaml error for both couchpotato and calibre-web

### ISSUE THREAD

**Issue by geneliu** [k8s-at-home/charts#377]
helm install couch k8s-at-home/couchpotato -f couchpotato.yml
Error: template: couchpotato/templates/common.yaml:1:3: executing "couchpotato/templates/common.yaml" at <include "common.all" .>: error calling include: template: couchpotato/charts/common/templates/_all.tpl:19:6: executing "common.all" at <include "common.pvc" .>: error calling include: template: couchpotato/charts/common/templates/_pvc.tpl:8:19: executing "common.pvc" at <$PVC.enabled>: can't evaluate field enabled in type interface {}

**Comment by bjw-s** [comment]
Hi! We'll need some more info to determine what is going on...
What version of the charts are you running, and do you have a (redacted if required) copy of the values you are running it with?

**Comment by onedr0p** [comment]
@geneliu please share your `couchpotato.yml` and `calibre-web.yml` it's hard to support without seeing what you are doing. Also feel free to jump on Discord.

**Comment by geneliu** [comment]
I should include those info when I opened the issue. 
`helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
`
`cat couchpotato.yml 
# Example values for my home-assistant.
# This is a YAML-formatted file.
image:
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
  - mycouch.example.com
persistence:
  enabled: true
env:
  TZ: America/Toronto
additionalVolumes:
  - name: local-k8sdata
    hostPath:
      path: /data2/k8sdata/video
      type: Directory
additionalVolumeMounts:
  - name: local-k8sdata
    mountPath: /media`

**Comment by onedr0p** [comment]
@geneliu please format your yaml in code blocks.

**Comment by onedr0p** [comment]
@geneliu take a look at the chart options `persistence.enabled` is not a valid field.

https://github.com/k8s-at-home/charts/blob/master/charts/couchpotato/values.yaml

Also Radarr is much better than Couchpotato :P

**Comment by geneliu** [comment]
@onedr0p 
FYI. Removed the persistence.enabled, got the same error. Will try Radarr for sure.

**Comment by onedr0p** [comment]
> @onedr0p 
> 
> FYI. Removed the persistence.enabled, got the same error. Will try Radarr for sure.

Make sure you are on the most recent chart version. 

Here's an example of my values.yaml in `HelmRelease` spec. Everything below `values:` is what you want. 

https://github.com/onedr0p/home-cluster/blob/main/cluster/media/radarr.yaml#L19

**Comment by bjw-s** [comment]
> @onedr0p
> FYI. Removed the persistence.enabled, got the same error. Will try Radarr for sure.

Also the error you are getting when you remove persistence is different:
```
error calling include: template: couchpotato/charts/common/templates/classes/_ingress.tpl:41:15: executing "common.classes.ingress" at <.host>: can't evaluate field host in type interface {}
```

This is due to your ingress values not being correct.

**Comment by geneliu** [comment]
Here is what I tried:
1. helm repo update
2. Removed persistence.enabled and corrected the ingress host setting as -
```yaml
image:
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - host: mycouch.example.com
env:
  TZ: America/Toronto
additionalVolumes:
  - name: local-k8sdata
    hostPath:
      path: /data2/k8sdata/video
      type: Directory
additionalVolumeMounts:
  - name: local-k8sdata
    mountPath: /media
```
3. helm install (`helm install couch k8s-at-home/couchpotato -f ./couchpotato.yml`)
```bash
Error: template: couchpotato/templates/NOTES.txt:1:4: executing "couchpotato/templates/NOTES.txt" at <include "common.notes.defaultNotes" .>: error calling include: template: couchpotato/charts/common/templates/_notes.tpl:9:63: executing "common.notes.defaultNotes" at <first .paths>: error calling first: runtime error: invalid memory address or nil pointer dereference
```

**Comment by geneliu** [comment]
No idea why it's complaining templates/_notes.tpl

**Comment by onedr0p** [comment]
Maybe try updating to the latest helm version? I see you are on `v3.0.2`

**Comment by bjw-s** [comment]
Try it like this:

```
image:
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - host: mycouch.example.com
      paths:
        - path: /
env:
  TZ: America/Toronto
additionalVolumes:
  - name: local-k8sdata
    hostPath:
      path: /data2/k8sdata/video
      type: Directory
additionalVolumeMounts:
  - name: local-k8sdata
    mountPath: /media
```
