### ISSUE TITLE
[common] add inlineConfigMap and inlineSecret logic

### ISSUE THREAD

**Issue by lukasmrtvy** [k8s-at-home/charts#448]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

Would be nice to have some logic for setting inline config like:

```
inlineConfigMap:
  - name: foo
    stringData:
      config.ini: |
        [foo]
        username = "foo"
        password = "bar"
additionalVolumeMounts:
- name: config-volume
  mountPath: /config
  subPath: config.ini
additionalVolumes:
- name: config-volume
  configMap:
    name: foo
```

or 

```
inlineSecret:
  - name: foo
    stringData:
      config.ini: |
        [foo]
        username = "foo"
        password = "bar"
additionalVolumeMounts:
- name: config-volume
  mountPath: /config
  subPath: config.ini
additionalVolumes:
- name: config-volume
  secret:
    name: foo
```
similar to https://github.com/k8s-at-home/charts/blob/master/charts/adguard-home/values.yaml#L4

**Anything else you would like to add:**

There must be also logic for calculating checksum of secret, configmap and checksum label for deployment, statefulset for proper redeploy after secret, configmap change.

**Additional Information:**

no

**Comment by bjw-s** [comment]
I'm not 100% sure about the actual use case of this and if this is something we should solve in `common`:

* Configuration and secrets are very application-specific, and we solve that by adding a configMap (that can also leverage Helm language if desired) to the application chart if it's required / makes sense. Some examples of this are `network-ups-tools`, `zigbee2mqtt`. I'm not sure having just the stringData in the values.yaml file has much benefit over just providing your own configMap / secret.
* These files would be read-only which can cause all sorts of issues when being used in "just any" app that doesn't properly handle this. The same goes for setting permissions on the files.

**Comment by lukasmrtvy** [comment]
Its probably doable with: ( not sure if it will work )

```
initContainers:
 - name: config-preseed
   image: hairyhenderson/gomplate:v3.8.0-slim
   command: ['sh', '-c']
   args:
     - if [ -f /config/config/config.ini ]; exit 0 ; fi
     - |
       cat << EOF | gomplate -o /config/config/config.ini
       ... preseed ...
       [opensubtitles]
       username = "foo"
       password = {{getenv "PASSWORD"}}
       EOF
   env:
   - name: PASSWORD
     valueFrom:
       secretKeyRef:
         name: mysecret
         key: password
   volumeMounts:
   - mountPath: /config
     name: config
```

Point is to store preseeded config ( gomplate template in configmap, hardcoded config in secret ) nicely in k8s object.
