### ISSUE TITLE
How to use VPN addon with CoreDNS 

### ISSUE THREAD

**Issue by Chris-Barton** [k8s-at-home/charts#451]
Hi 

Whenever I enable VPN on for example the Sonarr container I cant get any DNS query to work 

I think this is due to the DNS queries being routed through the VPN and therefore when the pod tires to use a local address the query fails 

Could you advise if you expect this to work and if so how

Thanks

Chris

**Comment by bjw-s** [comment]
Well, the good news is that it _can_ work :-) The _how_ is a bit trickier, since that depends (among other things) on whether you use an OpenVPN or a Wireguard setup, and your specific desires.

Most VPN providers/configurations (both OpenVPN and Wireguard) will force all traffic over their VPN. If that is the case for your provider you must set up additional firewall rules that allow traffic to your local DNS resolver. For example, with the [OpenVPN image by dperson](https://github.com/dperson/openvpn-client), check out the `ROUTE_*` environment variables. 

This is how I had mine set up when I was still using OpenVPN: https://github.com/bjw-s/k8s-gitops/blob/b141172ae12c35168a42e0ac59ca86f7c261f001/deployments/downloads/qbittorrent/values.yaml.tmpl#L75

**Comment by Chris-Barton** [comment]
Hi thanks for the reply yep what you suggested worked great for anyone else wants to get this working i used the following config for the vpn addon



```yaml

  vpn:
    enabled: true
    type: openvpn
    openvpn:
      auth: ""

    env:
      ROUTE_1: "10.0.0.0/8"
      
    configFile: |-
```


Where my local network is 10.0.0.0 - 10.0.10.255  it may be necessary to also include the kubernetes internal network class if you want pods to support connections to other pods which in my setup was 10.42.0.0/16

In my case I have added 10.0.0.0/8 which covers all the range of the A class network 10.0.0.0 - 10.255.255.255 this is safe to do as ip ranges in any of the local network class can only be used for local networks and wont be used externally depending on your network class this may require the use of 172.16.0.0/12 or 192.168.0.0/16

As a finally point it would be nice if the helm chart had this an option for this directly along the lines of 

```yaml
  vpn:
    enabled: true
    type: openvpn
    openvpn:
      localNetwork: "10.0.0.0/8"
```

of if this could at the very least pull a value from the kubernetes network config to allow access to other services by default
