### ISSUE TITLE
[bitwardenrs] Allow for specifying web port for unprivileged pod

### ISSUE THREAD

**Issue by WojoInc** [k8s-at-home/charts#491]
# Details

**Helm chart name:** bitwardenrs

**Describe the solution you'd like:**
Allow for the changing of the web ui port, adding the following to the values.yaml:
```yaml
bitwardenrs:
  gui:
    # If you set a different port here, you must also provide it under env
    port: 80
```

**Anything else you would like to add:**

**Additional Information:**
This allows users to run the pod unprivileged, as non-root accounts cannot bind ports below 1024.
