### ISSUE TITLE
Bitwardenrs doesn't take the admin-token and the db password correctly

### ISSUE THREAD

**Issue by i5Js** [k8s-at-home/charts#511]
# Details

**Helm chart name and version:**

bitwardenrs-2.0.0

**Container name and tag:**

bitwardenrs/server:1.18.0

**What steps did you take and what happened:**

- I've created a secret yml file with admin token and db password to connect with the database. The fields names are bitwardenrs-token and TOKEN_PASSWORD. For the db password are bitwardenrs-db and DB-PASSWORD
- Installed via `helm install bitwarden k8s-at-home/bitwardenrs  --namespace bitwarden --values bitwardenrs-values --debug 
`
- It fails with the following message: `create Pod bitwarden-bitwardenrs-0 in StatefulSet bitwarden-bitwardenrs failed error: Pod "bitwarden-bitwardenrs-0" is invalid: spec.containers[0].env[2].valueFrom.secretKeyRef.key: Required value`
- Checking the debug info, I've found it's expecting fixed names for the admin token and db password if it's needed:
```
# Source: bitwardenrs/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-bitwardenrs
  labels:
    helm.sh/chart: bitwardenrs-2.0.0
    app.kubernetes.io/name: bitwardenrs
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/version: "1.18.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-token: "c0YyY2ZtN2hOSW0zZTZrUkJPSjAyaTBqQTFQcHhWZmFpMUk1SGoxWUNkSXhkMU5j"
---
```
```
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: "bitwardenrs-db"
                  key: "DB-PASSWORD"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "bitwardenrs-db"
                  key: ""

```
**What did you expect to happen:** 
It should be installed successfully

**Additional Information:**

There is no ConfigMap created.

**Comment by bjw-s** [comment]
Can you maybe share your (redacted) `values.yaml` file? That would really help with trying to see what is going on...

**Comment by i5Js** [comment]
Hi @bjw-s, thanks for your reply, sure:

```
# Default values for bitwardenrs.

replicaCount: 1

image:
  repository: bitwardenrs/server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

bitwardenrs:
  domain: <domain_name>
  signupsAllowed: false
  gui:
    # If you set a different port here, you must also provide it under env
    port: 80
  websockets:
    enabled: true
    port: 3012
  admin:
    enabled: true
    disableAdminToken: false
    existingSecret:
      enabled: true
      name: "bitwardenrs-token"
      tokenKey: "TOKEN_PASSWORD"
  # External database configuration.
  # Requires bitwardenrs/server >= 1.17.0 or bitwardenrs/server-{mysql,postgres} images
  # ref: https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend
  #      https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-PostgreSQL-Backend
  externalDatabase:
    enabled: true
    # Supported values: 'mysql', 'postgresql'.
    type: "mysql"
    # Database host. Required if external database is enabled.
    host: <ip>
    # Database port. Optional, default value is specific to the database backend.
    port: ""
    # Database name.
    database: "bitwardenrs"
    # Database user.
    user: <user>
    # Database password. Special characters must be escaped with percent encoding.
    password: ""
    # Use existing secret for database credentials.
    existingSecret:
      enabled: true
      name: "bitwardenrs-db"
      userKey: "DB-PASSWORD"
      # Special characters in the password value must be escaped with percent encoding.
      passwordKey: ""
  # Enable SMTP. https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration
  smtp:
    enabled: false
    # SMTP hostname, required if SMTP is enabled
    host: ""
    # SMTP sender e-mail address, required if SMTP is enabled
    from: ""
    # SMTP sender name, defaults to 'Bitwarden_RS'
    fromName: ""
    # Enable SSL connection
    ssl: true
    # SMTP port
    port: 587
    # SMTP username
    user: ""
    # SMTP password. Required is user is specified, ignored if no user provided
    password: ""
    # Use existing secret for SMTP authentication
    existingSecret:
      enabled: false
      name: ""
      userKey: ""
      passwordKey: ""
  # Enable Yubikey 2FA: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-Yubikey-OTP-authentication
  yubico:
    enabled: false
    # OTP verification server. Will use the default YubiCloud servers if not specified
    server: ""
    # API Client ID for OTP server. Ignored if existingSecret is provided.
    clientId: ""
    # API Secret Key for OTP server. Required if clientId is specified, ignored when using existingSecret.
    secretKey: ""
    # Use existing secret for API keys
    existingSecret:
      enabled: false
      name: ""
      clientIdKey: ""
      secretKeyKey: ""

env: {}
# If you plan to run the WebUI on a port other than port 80, specify that here:
# For example, if running the container as a non-root user.
#  ROCKET_PORT: "80"

persistence:
  type: statefulset
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  ## Persistent Volume storage class
  # storageClass: "-"
  ## Use existing Persistent Volume Claim
  existingClaim: "nfs-bitwarden"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8081
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  additionalSpec: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```

**Comment by bjw-s** [comment]
```yaml
   externalDatabase:
    enabled: true
    # Supported values: 'mysql', 'postgresql'.
    type: "mysql"
    # Database host. Required if external database is enabled.
    host: <ip>
    # Database port. Optional, default value is specific to the database backend.
    port: ""
    # Database name.
    database: "bitwardenrs"
    # Database user.
    user: <user>
    # Database password. Special characters must be escaped with percent encoding.
    password: ""
    # Use existing secret for database credentials.
    existingSecret:
      enabled: true
      name: "bitwardenrs-db"
      userKey: "DB-PASSWORD"
      # Special characters in the password value must be escaped with percent encoding.
      passwordKey: ""
```

In your values.yaml, the `passwordKey` is empty for the externalDatabase. That is required by https://github.com/k8s-at-home/charts/blob/7fc6b440e6e55cf167101a868037f8191145f3da/charts/bitwardenrs/templates/_database.tpl#L31. That should probably fix your error.
