### ISSUE TITLE
Consider more advanced container environment settings

### ISSUE THREAD

**Issue by lazyoldbear** [k8s-at-home/charts#538]
# Details

**Helm chart name:**

common

**Describe the solution you'd like:**

Earlier or later there will be a distinct need to use field references in environment., like:

```yaml
- env:  
  - name: NODE_NAME
    valueFrom: 
      fieldRef:
        apiVersion: v1 
        fieldPath: spec.nodeName
```

Currently it can only be done through completely hacking the container (putting a plug instead, and defining all through `additionalContainers`).

**Anything else you would like to add:**

Obviously, this is about improving this part in `lib/controller/_container.tpl`:
```yaml
  env:
  {{- range $key, $value := .Values.env }}
  - name: {{ $key }}
    value: {{ $value | quote }}
  {{- end }}
  {{- end }}
```
