### ISSUE TITLE
[plex] Ability to disable /config mount (and use extraMounts and NFS)

### ISSUE THREAD

**Issue by hcsaustrup** [k8s-at-home/charts#551]
The latest release will either create a PVC or use an existing claim for /config. I'd like to be able to completely disable that, so I can mount something else on /config, i.e. a NFS volume.

Thanks! :-)

**Comment by bjw-s** [comment]
If believe if you wish to mount an existing NFS share to /config you _could_ create a PVC that references the NFS share, and use that as the value for `claimName`.

**Comment by spyder007** [comment]
If you are using NFS, it might be helpful to install an external provisioner (I've had luck with [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)).  Installing the provisioner will allow you to create one or more storage classes.  You can then define a storage class in the values for the PVC, and, in the case of the subdir provisioner, you'll get a subdirectory that represents the volume.

If you're storing media files in there, though, and you don't want them deleted, make sure you set the OnDelete and ArchiveOnDelete properties accordingly so that you don't wipe your NFS volume if you delete the plex install.

**Comment by brunnels** [comment]
Easiest would be just define the `existingClaim`
```
persistence:
  config:
    enabled: true
    skipuninstall: true
    existingClaim: pvc-plex-config
```

If you want to completely overide the `persistence` functionality you can define `additionalVolumes` and `additionalVolumeMounts` in your chart values.yml

Check out the volume template.  https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/templates/lib/controller/_volumes.tpl

```
persistence:
  config:
    enabled: false
additionalVolumes:
  - name: pvc-plex-config
    persistentVolumeClaim:
      claimName: pvc-plex-config
additionalVolumeMounts:
  - name: pvc-plex-config
    mountPath: "/config"
```
You can create the nfs pv and pvc like this:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    app: media
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-plex-config
  labels:
    pv: pv-plex-config
spec:
  capacity:
    storage: 200Gi
  nfs:
    server: 10.0.0.5
    path: /mnt/user/appdata/plex-config
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: media
  name: pvc-plex-config
  labels:
    pvc: pvc-plex-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv: pv-plex-config
  resources:
    requests:
      storage: 200Gi
```
