### ISSUE TITLE
[common] k8s 1.20 complains about volume name

### ISSUE THREAD

**Issue by gandazgul** [k8s-at-home/charts#584]
I'm trying to upgrade to the latest home-assistant chart but k8s is rejecting the Deployment spec because the config volume name is 0 and it expects a string:

```
helm.go:81: [debug] Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.EnableServiceLinks: DNSPolicy: Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: v1.VolumeMount.SubPath: Name: ReadString: expects " or n, but found 0, error found in #10 byte of ...|","name":0,"subPath"|..., bigger context ...|1},"volumeMounts":[{"mountPath":"/config","name":0,"subPath":"configs/hass"}]}],"dnsPolicy":"Cluster|..
```

In the common chart I see that the name is $index I think it should be changed to $name | default $index | quote? what do you think? I can make a PR for this.

Or am I missing something?

```
- name: home-assistant
  namespace: default
  chart: k8s-at-home/home-assistant
#  version: 4.0.0
  values:
    - image:
        tag: stable
        pullPolicy: Always
    - hostNetwork: true
    - ingress:
        enabled: true
        hosts:
          - host: hass.{{ requiredEnv "INGRESS_EXTERNAL_NAME" }}
            paths:
              - path: /
        tls:
        - hosts:
          - hass.{{ requiredEnv "INGRESS_EXTERNAL_NAME" }}
          secretName: hass-cert
        annotations:
          kubernetes.io/ingress.class: "nginx"
#          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.org/websocket-services: home-assistant
    - persistence:
      - enabled: true
        existingClaim: yasr-volume
        subPath: "configs/hass"
        mountPath: "/config"
    - vscode:
        enabled: true
        service:
          port: 8080
        ingress:
          enabled: true
          hosts:
            - host: hass-config.{{ requiredEnv "INGRESS_INTERNAL_NAME" }}
              path: /
          tls:
          - hosts:
            - hass-config.{{ requiredEnv "INGRESS_INTERNAL_NAME" }}
            secretName: hass-config-k8s-cert
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "ca-issuer"
            ```
