### ISSUE TITLE
[bitwardenrs] bitwardenrs.smtp.password value not used

### ISSUE THREAD

**Issue by coolguy1771** [k8s-at-home/charts#647]
# Details

**Helm chart name and version:**

bitwardenrs 2.0.0

**Container name and tag:**

bitwardenrs/server:1.19.0-alpine

**What steps did you take and what happened:**

deployed the chart with smtp as per the readme and comments inside of values.yaml

**Relevant Helm values:**

```yaml
bitwardenrs:
  smtp:
    password: "$BITWARDEN_SMTP_PASSWORD"
```

**What did you expect to happen:**

Example values to be used

**Additional Information:**

A quick look at the chart template I didn't see this value used at all.\
