### ISSUE TITLE
[homebridge] Service Endpoints not registered

### ISSUE THREAD

**Issue by airen29** [k8s-at-home/charts#654]
# Details

**Helm chart name and version:**

k8s-at-home/homebridge:1.0.2

**Container name and tag:**

oznu/homebridge:3.1.0

**What steps did you take and what happened:**

Installed Homebridge, enabled ingress over ClusterIP. Service does not have server IP's (looks like label selector does not work properly)

**Relevant Helm values:**

```yaml
ingress:
  enabled: true
  hosts:
  - homebridge.192.168.1.68.nip.io
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  loadBalancerIP: 192.168.1.68
  httpPort: 80
  annotations:
    traefik.http.routers.homebridge.entrypoints: web, websecure
    traefik.http.routers.homebridge.rule: Host(`homebridge.192.168.1.68.nip.io`)
    traefik.http.routers.homebridge.middlewares: homebridge, https
    traefik.http.middlewares.homebridge.addprefix.prefix: /
    traefik.http.services.homebridge.loadbalancer.server.port: "80"
    traefik.http.middlewares.https.redirectscheme.scheme: https
config:
  enableUI: true
  plugins:
  - homebridge-hue
  - homebridge-weather-plus
  - homebridge-mi-airpurifier
  - homebridge-pihole
 ```

**What did you expect to happen:**

Endpoints should be registered in service

**Anything else you would like to add:**

![image](https://user-images.githubusercontent.com/22710264/110781018-a535b400-8265-11eb-8cc5-2403f9ea999f.png)
