### ISSUE TITLE
Bazarr documentation request / help with service/ingress

### ISSUE THREAD

**Issue by Shamazo** [k8s-at-home/charts#702]
# Details

**Helm chart name: Bazarr**

**Describe the solution you'd like:**

Hi, I am very much appreciate if someone could point me to some documentation (or if you are super amazing write some) for the Bazarr chart. I managed to get it installed on my cluster, but I am trying to figure out what chart/container settings need to be set to be able to expose it on my LAN. 

I tried this in the values.yaml
```
service:
  type: ClusterIP
  port:
    port: 80
    name: bazarr
```

along with this ingress (which covers my other media related services):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "media"
  name: "media-ingress"
spec:
  rules:
  - host: "my.domain"
    http:
      paths:
        - backend:
            serviceName: "transmission-transmission-openvpn"
            servicePort: 80
          path: "/transmission"
        - backend:
            serviceName: "sonarr"
            servicePort: 80
          path: "/sonarr"
        - backend:
            serviceName: "jackett"
            servicePort: 80
          path: "/jackett"
        - backend:
            serviceName: "radarr"
            servicePort: 80
          path: "/radarr"
        - backend:
            serviceName: "bazarr"
            servicePort: 80
          path: "/bazarr"
```
