### ISSUE TITLE
[statping] hardcoded env causes undesired results

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/charts#747]
# Details

**Helm chart name and version:**

statping-3.1.1

**Container name and tag:**

N/A

**What steps did you take and what happened:**

Defined some values via `env:` and some via `envFrom:`

**Relevant Helm values:**

```yaml
  env:
    NAME: cajun.pro status
    DESCRIPTION: cajun.pro hosting status page
    VIRTUAL_HOST: https://status.cajun.pro
    DB_CONN: postgres
    DB_HOST: postgres-statping
    DB_DATABASE: postgres
  envFrom:
    - secretRef:
        name: statping
```
https://github.com/DirtyCajunRice/GitOps-Argo-CD/blob/2ebaec880e25deee3cdba1aa09a44e7237f11449/statping/values.yaml

**What did you expect to happen:**

for only the values i defined in env to be used

**Anything else you would like to add:**

N/A

**Additional Information:**

Adding a check for `ENVVARNAME: "-"` is going to be too verbose. Some type of globally set var should toggle using all defaults or none. There are workarounds for wiping the env dict like `env: ~` but that doesnt work when the chart checks and sets anyway.

**Comment by bjw-s** [comment]
This is by design in all Helm charts though: if a chart has a set of default values set in `values.yaml`, any user-provided values  are overridden and/or appended. Anything that is not provided by the user will then be set to the default value.

The only way we could circumvent that is by not providing any default env values in the chart, and/or comment them out so that they are only provided as a sort of guide.

**Comment by onedr0p** [comment]
Ideally we should migrate this over the the common library :)

**Comment by bjw-s** [comment]
statping is already migrated ;)
https://github.com/k8s-at-home/charts/tree/master/charts/stable/statping

**Comment by onedr0p** [comment]
ignore me, on mobile 😅

**Comment by DirtyCajunRice** [comment]
Right but some of these values are not something everyone wants to have in a public repo, and the way the priority is set in k8s for env vars the envFrom is overwritten by env

**Comment by DirtyCajunRice** [comment]
Here is a blatant example:
current code: 

https://github.com/k8s-at-home/charts/blob/a3ac7d6c76fcd06a32693a7f4d69746308c96b35/charts/stable/statping/templates/common.yaml#L7-L22

And if you disable postgres... and verbosely disable the environment variables it still is setting the `DB_HOST`, `DB_USER` and `DB_PASS` and `DB_DATABASE` variables from the postgres chart you arent using. 

I would prefer to not have to have my config look like
```yaml
  env:
    ...
    ADMIN_USER: ""
    ADMIN_PASSWORD: ""
    ADMIN_EMAIL: ""
    DB_USER: ""
    DB_PASS: ""
  envValueFrom:
    ADMIN_USER:
      secretKeyRef:
        name: "statping"
        key: admin-user
    ADMIN_PASSWORD:
      secretKeyRef:
        name: "statping"
        key: admin-password
    ADMIN_EMAIL:
      secretKeyRef:
        name: "statping"
        key: admin-email
    DB_USER:
      secretKeyRef:
        name: "statping"
        key: username
    DB_PASS:
      secretKeyRef:
        name: "statping"
        key: password
```

it already is unfortunate that i have to define the env values in the first place when realistically all i should have to put is
```yaml
env:
  ...
envFrom:
  - secretRef:
      name: "statping"
```

The ultimate statement here is that by forcing all of these to exist in `env:` you completely disable/negate the common chart's ability to use `envTpl, envFrom, and envValeFrom` for those variables
