### ISSUE TITLE
ARM images?

### ISSUE THREAD

**Issue by clambin** [k8s-at-home/charts#815]
# Details

**Helm chart name and version:**

jackett 9.0.0

**Container name and tag:**

ghcr.io/k8s-at-home/jackett:v0.17.931

**What steps did you take and what happened:**

Just upgraded the helm chart for Jackett to v9.0.0.   This moves away from linuxserver builds on hub.docker.com to ghr.io.  Now I'm getting an error:

```
Failed to pull image "ghcr.io/k8s-at-home/jackett:v0.17.908": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/k8s-at-home/jackett:v0.17.908": no match for platform in manifest: not found
```

Not sure how to inspect manifests on ghrc.io, but from what I've seen, I think it only include amd64 builds? So this change in v9.0.0 breaks for users on ARM devices.

**Relevant Helm values:**

```
    image:
      repository: ghcr.io/k8s-at-home/jackett
      pullPolicy: IfNotPresent
      tag: v0.17.931
    env:
      TZ: "Europe/Brussels"
      PUID: "1000"
      PGID: "1000"
    persistence:
      config:
        enabled: true
        existingClaim: "pvc-jackett-config"
      downloads:
        enabled: true
        mountPath: /downloads
        existingClaim: "pvc-transmission-downloads"
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
```

I supplied the image tags to see if the problem was only related to tag: v0.17.908 (which is in the chart's values), but I'm getting the same problem.

**What did you expect to happen:**

Still having a working system after upgrading to v9.0.0.
