### ISSUE TITLE
transmission initcontainer issue

### ISSUE THREAD

**Issue by jr0dd** [k8s-at-home/charts#839]
# Details

**Helm chart name and version:**

transmission 6.0.0

**Container name and tag:**

k8s-at-home/transmission:v3.00

**What steps did you take and what happened:**

Using the initcontainer to pull the theme, curl can not resolve github.com. It appears that the initcontainer doesn't make a network connection. I changed the image value from curl to ubuntu focal and same thing. This may be a limitation of initcontainers.

**Relevant Helm values:**
I just added the commands to a custom startup probe to get it working

```
probes:
  liveness:
    spec:
      timeoutSeconds: 30
  readiness:
    spec:
      timeoutSeconds: 30
  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command:
        - "bash"
        - "-c"
        - curl -fsSL -o /tmp/flood-for-transmission.tar.gz
          "https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz"
          && mkdir -p /config/flood
          && tar -xzf /tmp/flood-for-transmission.tar.gz --strip-components 1 -C /config/flood
      initialDelaySeconds: 0
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 3
```

It feels kind of hacky to me, but does the job
