### ISSUE TITLE
[appdaemon] persistence uses wrong mount folder

### ISSUE THREAD

**Issue by tarioch** [k8s-at-home/charts#899]
# Details

**Helm chart name and version:**

appdaemon 5.1.0

**What steps did you take and what happened:**

I enabled persistence and it didn't work.

**Relevant Helm values:**

```yaml
persistence:
  config:
    enabled: true
```

**What did you expect to happen:**

The configuration is taken from my pv/pvc

**Anything else you would like to add:**

The problem is that appdaemon doesn't expect a mount /config but instead a mount /conf
if I create a values config with

```yaml
persistence:
  conf:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
```

It works
