### ISSUE TITLE
[powerdns] Powerdns chart do not works with postgres

### ISSUE THREAD

**Issue by NaPs** [k8s-at-home/charts#94]
The Powerdns chart do not works with a postgres database.

When configuring the chart to use a postgres database, for example with the following values:

```
powerdns:
  postgres:
    username: pdns
    password: mysecret
    database: pdns
    
mariadb:
  enabled: false

postgres:
  enabled: true
  postgresqlUsername: pdns
  postgresqlPassword: mysecret
  postgresqlDatabase: pdns
```

The powerdns pod ends up with the following errors in its logs:

```
ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
Waiting for database to come up
```

It looks that the underlying image used by this chart (psitrax/powerdns) only support mysql: https://github.com/psi-4ward/docker-powerdns/issues/22
