### ISSUE TITLE
home-assistant 9.0.x break prometheus.serviceMonitor

### ISSUE THREAD

**Issue by morremeyer** [k8s-at-home/charts#983]
# Details

**Helm chart name and version:** home-assistant 9.0.1

**Container name and tag:** not relevant

**What steps did you take and what happened:**

I upgraded to 9.0.0/9.0.1.

The `ServiceMonitor` can’t be rendered anymore due to 

```
Error: Failed to render chart: exit status 1: Error: template: home-assistant/templates/servicemonitor.yaml:16:35: executing "home-assistant/templates/servicemonitor.yaml" at <.Values.service.port.name>: nil pointer evaluating interface {}.name
```

**Relevant Helm values:**

```
prometheus:
  serviceMonitor:
    enabled: true
    bearerTokenSecret:
      name: prometheus-secret
      key: token
```

**What did you expect to happen:** Chart rendering

**Anything else you would like to add:**

The issue is in [the servicemonitor.yaml template](https://github.com/k8s-at-home/charts/blob/0c85e0494653c08e9867a2a18a30433c9fc6ed6f/charts/stable/home-assistant/templates/servicemonitor.yaml#L16):

```
port: {{ default "http" .Values.service.port.name }} 
```
