### ISSUE TITLE
Home Assistant Service Monitor reference issue

### ISSUE THREAD

**Issue by jorneilander** [k8s-at-home/charts#993]
https://github.com/k8s-at-home/charts/blob/e062593a2f08c05fc9e9ba1c5e30466c8e74602e/charts/stable/home-assistant/templates/servicemonitor.yaml#L16

This line refers to `.Values.service.port.name`, but `{}.name` doesn't exist. The structure is:
```YAML
service:
  main:
    ports:
      http:
        port: 8123
```

Unrelated, doesn't `ports` (plural) imply a list (of dicts) instead of a dict? Not sure what the convention is throughout all templates.
